NOISSUE - Add new /disconnect endpoint documentation
absmach/supermq-docs pull request #100
Opened 2021-07-13 12:23 UTC by buraksekili

Signed-off-by: Burak Sekili <buraksekili@gmail.com>

### What does this do?
This PR adds documentation about the new `/disconnect` endpoint.

### Which issue(s) does this PR fix/relate to?
`-`
### List any changes that modify/break current functionality
`-`
### Have you included tests for your changes?
`-`
### Did you document any new/modified functionality?
Yes
### Notes

2021-07-13 13:11 UTC, manuio requested changes

2021-07-13 13:11 UTC, manuio commented on docs/api.md
> +```
You can use ````bash` here

2021-07-14 12:06 UTC, manuio approved these changes
LGTM

2021-07-14 13:30 UTC, blokovi approved these changes

2021-07-14 13:41 UTC, nmarcetic approved these changes

2021-07-14 13:42 UTC, merged