MF-101 - Add Authorization section for Policies
absmach/supermq-docs pull request #102
Opened 2021-09-10 07:26 UTC by buraksekili

Signed-off-by: Burak Sekili <buraksekili@gmail.com>

### What does this do?

This PR adds a new section related to policies.

### Which issue(s) does this PR fix/relate to?

Resolves #101 

### List any changes that modify/break current functionality

`-`

### Have you included tests for your changes?
`-`
### Did you document any new/modified functionality?
Yes
### Notes

2021-09-13 11:13 UTC, manuio commented on docs/authorization.md
> +curl -isSX POST http://localhost/things/a1109d52-6281-410e-93ae-38ba7daa9381/share -d '{"user_id":"user_id_2", "policies": ["read", "delete"]}' -H "Authorization: <user1_auth_token>" -H 'Content-Type
It would be clearer to use `"user_id": "<user_id>"`

2021-09-13 18:22 UTC, drasko requested changes

2021-09-13 18:22 UTC, drasko commented on docs/authorization.md
> +Mainflux uses policies to control permissions on entities: **users**, **things**, and **groups**. Under the hood, Mainflux uses [ORY Keto](https://www.ory.sh/keto/) that is the first and only open-so
You can remove this `first and only`, keeps sentence simpler.

2021-09-13 18:22 UTC, drasko commented on docs/authorization.md
> +Policies define permissions for the entities. For example, *which user* has *access* to *a specific thing*? Such policies have three main components: **subject**, **object**, and **relation**.
`For example, *which user* has *access* to *a specific thing*?` - is this a question, or example - if not a question do not finish it with a question mark.

2021-09-13 18:22 UTC, drasko commented on docs/authorization.md
> +As we expected, the operation is successfully done. The policy server checked that `is user2 allowed to view "user1-thing"`? Since `user2` has a `read` policy on `"user1-thing"`, the Policy server al
`is user2 allowed to view "user1-thing"`? -probably you wanted to keep question mark under these verbatim quotes. If not - the whole sentence is not a question (only policy condition is), so do not put it at the end of that overall sentence.

2021-09-13 18:22 UTC, drasko commented on docs/authorization.md
> +- By default, Mainflux allows anybody to create a user. If you disable this default policy, only *admin* is able to create a user.
Maybe add here that this default policy can be disabled through env var in deployment time.

2021-09-13 18:22 UTC, drasko commented on docs/authorization.md
> +curl -isSX POST http://localhost/things/a1109d52-6281-410e-93ae-38ba7daa9381/share -d '{"user_id":"<user_id>", "policies": ["read", "delete"]}' -H "Authorization: <user1_auth_token>" -H 'Content-Type
Probably `"user_id":"<user2_id>"` would be better explication of this example (since you already used `user1` and `user2`).

2021-09-13 18:22 UTC, drasko commented on docs/authorization.md
> +After identifying the requester as `user2`, the Policy service checks that `user2 is allowed to view the "user1-thing"`? Since `user2` has no such policy, the Policy service denies this request.
Insert question mark in verbatim quote, if it is needed

2021-10-20 20:25 UTC, drasko requested changes

2021-10-20 20:25 UTC, drasko commented on docs/authorization.md
> +This default policy can be disabled through an environment variable in deployment time.
Explain here which env var.

2021-10-20 20:25 UTC, drasko commented on docs/authorization.md
> +Mainflux comes with predefined policies.
Maybe we should list which predefined policies. If this is not clear for now, they we'll explain it later. If those are the policies that you list below in subtopics, then say that (because on the first read it is not clear).

2021-10-20 20:25 UTC, drasko commented on docs/cli.md
> +mainflux-cli users create <user_email> <user_password> <user_auth_token>
Why both password AND token need to be added?

2021-10-20 20:53 UTC, buraksekili commented on docs/cli.md
> +mainflux-cli users create <user_email> <user_password> <user_auth_token>
Either only admin or everybody is allowed to create a new user. If everybody is allowed to create a user (defined through environment variable), the policy service doesn't check the token. Otherwise, the token is needed to verify that the requester is admin.

For example in [here](https://github.com/buraksekili/mainflux/blob/0582947204a1dd43c6cb7eb49737c1c1d6ecb4d1/users/service.go#L190), `checkAuthz` takes a token and checks `is anybody allowed to create a user`. If not all users are able to create a user, then `checkAuthz` identifies the token and checks whether the requester is admin or not.

2021-10-20 21:24 UTC, buraksekili commented on docs/authorization.md
> +Mainflux comes with predefined policies.
I forgot some policies to define here, for instance, policies related to groups. I will add them

2021-10-20 21:31 UTC, drasko commented on docs/cli.md
> +mainflux-cli users create <user_email> <user_password> <user_auth_token>
This should be explained in the doc then.

2021-10-26 03:21 UTC, arvindh123 submitted a review, later dismissed
Looks Good To Me, 
Mainflux `master` `docs`  doesn't have `cli` related to `groups`, so I'm not expecting `groups policies`  related `cli`

2021-10-26 03:26 UTC, arvindh123 commented on docs/cli.md
> +mainflux-cli users create <user_email> <user_password> <user_auth_token>
Here we can should two commands , like if env  variable MF_ONLY_ADMIN_CREATES_USER   is set ,
then use  `mainflux-cli users create <user_email> <user_password> <user_auth_token>`
else use `mainflux-cli users create <user_email> <user_password>`


```suggestion
if env `MF_ONLY_ADMIN_CREATES_USER`  is set then   
`mainflux-cli users create <user_email> <user_password> <user_auth_token>`
else   
`mainflux-cli users create <user_email> <user_password>`
```

2021-10-26 04:35 UTC, drasko commented on docs/cli.md
> +mainflux-cli users create <user_email> <user_password> <user_auth_token>
CLI is used on a client node, where there is no need for this ENV var (which is used for server deployment). Explanation in the doc should be enough.

2021-11-03 20:04 UTC, blokovi submitted a review, later dismissed

2021-11-03 20:40 UTC, drasko requested changes

2021-11-03 20:40 UTC, drasko commented on docs/authorization.md
> +Mainflux comes with predefined policies.
Please add those

2021-11-03 20:40 UTC, drasko commented on docs/cli.md
> +mainflux-cli users create <user_email> <user_password> <user_auth_token>
Please add this

2021-11-05 12:37 UTC, drasko submitted a review, later dismissed
LGTM

2021-11-08 09:40 UTC, dusanb94 requested changes

2021-11-08 09:40 UTC, dusanb94 commented on docs/api.md
> +```
It would be nice to write a short explanation of what this means. Something like: each user from the group will be able to do this-and-this on all the things from the things group (Similar to what's explained in Group entity-related policies).

2021-11-08 09:40 UTC, dusanb94 commented on docs/cli.md
> +> Mainflux has two options for user creation. Either everybody or just the admin is able to create new users. This option is dictated through policies and be configured through environment variable (
This explanation should go before bash examples.

2021-11-08 09:40 UTC, dusanb94 commented on docs/authorization.md
> +## Delete policies
While it's intuitive for the end-user, it would be nice to have a short explanation of what's the effect of policy deletion.

2021-11-08 10:50 UTC, dborovcanin requested changes

2021-11-08 10:50 UTC, dborovcanin commented on docs/authorization.md
> +Now, all the members of the `user_group` have access to things grouped by `thing_group`. Therefore, `user@example.com` has `read`, `write` and `delete` policies on the things within the thing_group.
... within the `thing_group`.

2021-11-08 10:50 UTC, dborovcanin commented on docs/authorization.md
> +
Please remove one empty line.

2021-11-08 10:50 UTC, dusanb94 commented on docs/authorization.md
> +
Please remove one empty line.

2021-11-08 10:58 UTC, dusanb94 approved these changes

2021-11-08 11:04 UTC, drasko approved these changes
LGTM

2021-11-08 11:04 UTC, merged