Bump CLI version in Get Started
absmach/supermq-docs pull request #105
Opened 2021-11-29 09:11 UTC by ele7ija

Signed-off-by: bp <bpoprzen@gmail.com>

### What does this do?

Bumps CLI version in the Get Started.

### Which issue(s) does this PR fix/relate to?
Resolves #104 

### List any changes that modify/break current functionality
`-`

### Have you included tests for your changes?
`-`

### Did you document any new/modified functionality?
No

### Notes

2021-11-29 09:52 UTC, dusanb94 approved these changes, later dismissed

2021-11-29 12:13 UTC, manuio requested changes

2021-11-29 12:13 UTC, manuio commented on docs/getting-started.md
> +which can be downloaded as a tarball from GitHub (here we use release `0.12.0` but be sure to use the [latest CLI release](https://github.com/mainflux/mainflux/releases)):
It would be better to use `0.12.1`  here

2021-11-29 12:13 UTC, manuio commented on docs/getting-started.md
> +wget -O- https://github.com/mainflux/mainflux/releases/download/0.12.0/mainflux-cli_0.12.0_linux-amd64.tar.gz | tar xvz -C $GOBIN
I'm going to upload `mainflux-cli_0.12.1_linux-amd64.tar.gz`  so we can use `0.12.1`

2021-11-30 08:45 UTC, ele7ija commented on docs/getting-started.md
> +wget -O- https://github.com/mainflux/mainflux/releases/download/0.12.0/mainflux-cli_0.12.0_linux-amd64.tar.gz | tar xvz -C $GOBIN
done

2021-11-30 08:45 UTC, ele7ija commented on docs/getting-started.md
> +which can be downloaded as a tarball from GitHub (here we use release `0.12.0` but be sure to use the [latest CLI release](https://github.com/mainflux/mainflux/releases)):
done

2021-11-30 12:49 UTC, manuio submitted a review, later dismissed
LGTM

2021-11-30 13:45 UTC, manuio commented
@ele7ija Update your branch please

2021-12-01 16:38 UTC, ele7ija commented
> @ele7ija Update your branch please

branch updated (rebased)

2021-12-01 16:47 UTC, blokovi approved these changes

2021-12-01 17:31 UTC, manuio approved these changes
LGTM

2021-12-01 17:31 UTC, merged