#108 Update the things API about how to create things with external ID
absmach/supermq-docs pull request #109
Opened 2021-12-08 12:02 UTC by qs-wang

Update teh channels API about how to create channels with external ID

Signed-off-by: Q.S. Wang <wangqs_eclipse@yahoo.com>

Pull request title should be `MF-XXX - Support external UUIDs for Things and Channels #1425` 

### What does this do?
Update the things API about how to create things with external ID
Update teh channels API about how to create channels with external ID

### Which issue(s) does this PR fix/relate to?
`Resolves #108`

2021-12-08 12:25 UTC, dusanb94 requested changes

2021-12-08 12:25 UTC, dusanb94 commented on docs/api.md
> +To create a thing with an external ID, which could be from external Application or Service which is managing the Mainflux, you need the thing with a valid UUID and a `user_token`
Since these are the formal docs, don't spare words. Something like a short introduction can be nice here, for example:

> Often case the user will want to integrate the existing solutions with the Mainflux platform. To simplify integration and avoid artificial cross-platform reference (such as special fields in Mainflux Things metadata), it is possible to set Mainflux Thing ID on during Thing creation. That way, the user can set the existing ID as a newly created Thing ID to keep reference between Thing and the artifact that Thing represents. There are two limitations - Thin ID needs to be in UUID V4 format and it needs to be unique in the Mainflux domain.

2021-12-08 16:03 UTC, drasko submitted a review, later dismissed
LGTM

2021-12-08 16:26 UTC, dusanb94 requested changes

2021-12-08 16:26 UTC, dusanb94 commented on docs/api.md
> +It is often the case that the user will want to integrate the existing solutions, e.g. an asset management system, with the Mainflux platform. To simplify the integration between the systems and avoi
Fx typo `the user can set the the`.

2021-12-08 16:26 UTC, dusanb94 commented on docs/api.md
> +There are two limitations - the existing ID have to be in UUID V4 format and it needs to be unique in the Mainflux domain.
...has to be...

2021-12-08 16:26 UTC, dusanb94 commented on docs/api.md
> +To create a thing with an external ID, you need provide the UUID v4 format ID together with thing name, and other field as well as a `user_token`
...and other fields...

2021-12-08 16:26 UTC, dusanb94 commented on docs/api.md
> +Channel is a group of things which could represent a special category in existing systems, e.g. a building level channel could represent the level of a smarting building system. For helping to keep t
..that could represent...set an existing ID while creating...has to be in UUID v4...

2021-12-09 10:55 UTC, dusanb94 approved these changes

2021-12-09 17:44 UTC, manuio approved these changes
LGTM

2021-12-09 19:32 UTC, drasko approved these changes
LGTM

2021-12-09 19:32 UTC, merged