NOISSUE - Add transformer config
absmach/supermq-docs pull request #110
Opened 2021-12-08 12:10 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

### What does this do?
Add transformer `format` (SenML or JSON), `content_type` and `time_fields` configuration doc.

### Notes
Related to: https://github.com/mainflux/mainflux/pull/1514

2021-12-08 16:19 UTC, dusanb94 commented on docs/storage.md
> +For the JSON transformer you can configure `time_fields` in the `[transformer]` section to use arbitrary fields from the JSON message payload as timestamp. `time_fields` is represented by an array of
Maybe it would be a good idea to explain the motivation behind this. Like:
> Usually, the payload of the IoT message contains message time. It can be in different formats (like base time and record time in the case of SenML) and the message field can be under the arbitrary key. Usually, we would want to map that time to the Mainflux Message field `Created` and for that reason, we need to configure the Transformer to be able to read the field, parse it using proper format and location (if devices time is different than the service time), and map it to Maifnlux Message.

2021-12-13 09:38 UTC, dusanb94 commented on docs/storage.md
> +Usually, the payload of the IoT message contains message time. It can be in different formats (like base time and record time in the case of SenML) and the message field can be under the arbitrary ke
Fix typo `Maifnlux`.

2021-12-14 09:28 UTC, dusanb94 approved these changes

2021-12-14 09:29 UTC, dusanb94 requested changes

2021-12-14 09:29 UTC, dusanb94 commented on docs/storage.md
> +For JSON transformer you can configure `time_fields` in the `[transformer]` section to use arbitrary fields from the JSON message payload as timestamp. `time_fields` is represented by an array of obj
Typo: `and a the time location`.

2021-12-14 09:32 UTC, dusanb94 approved these changes

2021-12-14 10:19 UTC, drasko approved these changes
LGTM

2021-12-14 10:20 UTC, merged