NOISSUE - Add API key documentation
absmach/supermq-docs pull request #112
Opened 2021-12-19 18:21 UTC by fbugarski

Signed-off-by: Filip Bugarski <filipbugarski@gmail.com>

### What does this do?
Add API key documentation.
### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2021-12-21 08:14 UTC, dusanb94 commented on docs/api.md
>  ### Gets API key details for the given key
Get API key details

2021-12-21 10:17 UTC, dusanb94 submitted a review, later dismissed

2021-12-29 15:46 UTC, blokovi approved these changes, later dismissed

2021-12-29 15:54 UTC, drasko requested changes

2021-12-29 15:54 UTC, drasko commented on docs/api.md
>  > Must-have: 'user_token' and 'key_id"
You probably meant `'key_id'`. not `'key_id"`?

2021-12-29 15:54 UTC, drasko commented on docs/api.md
>  > Must-have: 'user_token' and 'key_id"
Same above.

2021-12-29 15:57 UTC, fbugarski commented on docs/api.md
>  > Must-have: 'user_token' and 'key_id"
Yup :)

2022-01-05 19:55 UTC, drasko approved these changes
LGTM

2022-01-05 19:55 UTC, merged