NOISSUE - NOISSUE - Change endpoint /version by /health
absmach/supermq-docs pull request #119
Opened 2022-01-11 12:21 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2022-01-11 12:29 UTC, blokovi submitted a review, later dismissed

2022-01-19 22:33 UTC, drasko requested changes

2022-01-19 22:33 UTC, drasko commented on docs/edge.md
> +'{"status": "pass", "version":"0.12.1", "commit":"57cca9677721025da055c47957fc3e869e0325aa" , "description":"export service", "build_time": "2022-01-19_10:13:17"}'
Looing at [here](https://datatracker.ietf.org/doc/html/draft-inadarei-api-health-check-06#section-5), I do not see `"commit"` keyword in the standard. I think you must find and select something closest but tandardized - maybe `releaseId`.

2022-01-20 09:18 UTC, manuio commented on docs/edge.md
> +'{"status": "pass", "version":"0.12.1", "commit":"57cca9677721025da055c47957fc3e869e0325aa" , "description":"export service", "build_time": "2022-01-19_10:13:17"}'
I had the same thought but what about `build_time`? Or we decide to define all in the description or we decide to have custom fields.

2022-01-24 20:52 UTC, drasko approved these changes
LGTM

2022-01-24 20:52 UTC, drasko commented on docs/edge.md
> +'{"status": "pass", "version":"0.12.1", "commit":"57cca9677721025da055c47957fc3e869e0325aa" , "description":"export service", "build_time": "2022-01-19_10:13:17"}'
Resolved as per https://github.com/mainflux/mainflux/pull/1541#issuecomment-1020512332

2022-01-24 20:52 UTC, merged