MF-1373 - Change CoAP CLI doc
absmach/supermq-docs pull request #121
Opened 2022-01-21 13:00 UTC by fbugarski

Signed-off-by: Filip Bugarski <filipbugarski@gmail.com>

### Which issue(s) does this PR fix/relate to?
Resolves https://github.com/mainflux/mainflux/issues/1373

2022-01-21 20:27 UTC, drasko requested changes

2022-01-21 20:27 UTC, drasko commented on docs/messaging.md
> +To subscribe, send `GET` request with Observe option set to false. There are two ways to unsubscribe:
Should it be `false` or `0`? Because here uder, it says that `Observe` opeition should be `1`, not `true`. This needs to be calrified.

2022-01-25 13:21 UTC, fbugarski commented on docs/messaging.md
> +To subscribe, send `GET` request with Observe option set to false. There are two ways to unsubscribe:
https://github.com/mainflux/coap-cli/blob/master/cmd/main.go#L91

Flag `o` is bool it should be true or false.

2022-01-25 13:24 UTC, blokovi approved these changes

2022-01-25 13:25 UTC, drasko approved these changes
LGTM

2022-01-25 13:25 UTC, merged