NOISSUE - Add pagination of things and users to docs
absmach/supermq-docs pull request #125
Opened 2022-04-06 15:34 UTC by 0x6f736f646f

Signed-off-by: 0x6f736f646f <blackd0t@protonmail.com>

### What does this do?
It adds the documentation of pagination of things and users to the docs

### Which issue(s) does this PR fix/relate to?
NOISSUE

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
N/A

2022-04-08 10:27 UTC, manuio requested changes

2022-04-08 10:27 UTC, manuio commented on docs/api.md
> +You can get all users in the database by querying this endpoint. List all users request accepts limit and offset query parameters
`List all users request accepts limit, offsetm, name, email and metadata query parameters`

2022-04-08 10:27 UTC, manuio requested changes

2022-04-08 10:27 UTC, manuio commented on docs/api.md
> +> Must have: `user_token`, `offset`, `limit` and `name`
Must have should be only for user_token. Other filters are optional and have defautl values.

2022-08-23 12:33 UTC, dborovcanin commented on docs/api.md
> +> Must have: `user_token`, `offset`, `limit` and `name`
@0x6f736f646f Please resolve.

2022-08-23 12:52 UTC, manuio commented
@0x6f736f646f Can you please fix `{"channels":[{"id":"<xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxx1>","name":"channel_name_1"},{"id":"<xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxxxx2>","name":"channel_name_2"}]}` -> `{"channels":[{"id":"<channel_id_1>","name":"channel_name_1"},{"id":"<channel_id_2>","name":"channel_name_2"}]}`?

2022-08-23 15:21 UTC, 0x6f736f646f commented
> {"channels":[{"id":"<channel_id_1>","name":"channel_name_1"},{"id":"<channel_id_2>","name":"channel_name_2"}]}

I have done it for both channels and things

2022-08-23 17:55 UTC, manuio commented on docs/api.md
> +### Get All Channels
IMO `Get Channels` is better since this endpoint accept pagination and it's not necesserally all channels. If you revert this one fix `Get All Things` please

2022-08-24 12:10 UTC, manuio approved these changes
LGTM

2022-08-24 12:18 UTC, dborovcanin approved these changes

2022-08-24 13:12 UTC, merged