NOISSUE - Add Message Broker Documentation
absmach/supermq-docs pull request #127
Opened 2022-08-17 14:28 UTC by 0x6f736f646f

### What does this do?
It adds message broker documentation

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
N/A

2022-08-17 15:18 UTC, manuio requested changes

2022-08-17 15:18 UTC, manuio commented on docs/dev-guide.md
> +
You can simplify the first sentence with something like `If you want to change the default message broker to RabbitMQ, VerneMQ or Kafka you need to install it on the local system.` and do something similar with the links or even use them directly in the names.

2022-08-17 15:21 UTC, drasko requested changes

2022-08-17 15:21 UTC, drasko commented on docs/dev-guide.md
> +To do this you can check out the various methods of installing VerneMQ on your local system [here](https://kafka.apache.org/quickstart).
Installing Kafka

2022-08-18 22:24 UTC, drasko approved these changes
LGTM

2022-08-19 10:00 UTC, manuio approved these changes
LGTM

2022-08-23 11:03 UTC, dborovcanin approved these changes

2022-08-23 11:03 UTC, merged