NOISSUE - Add Change User Status Documentation
absmach/supermq-docs pull request #128
Opened 2022-08-18 13:33 UTC by 0x6f736f646f

### What does this do?
Add change user status to enabled and disabled for both `cli` and `api` documentations

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
N/A

2022-08-18 14:40 UTC, manuio commented on docs/cli.md
> +  -S, --status string          Status query parameter
Should we clarify that it's only for users?

2022-08-19 11:31 UTC, 0x6f736f646f commented on docs/cli.md
> +  -S, --status string          Status query parameter
I don't think so. It is the same thing with `--email`. I am suggesting we change the description for cli i.e 

`-e, --email string Email query parameter` becomes `-e, --email string User email query parameter` and `-S, --status string Status query parameter` becomes `-S, --status string User status query parameter`

2022-08-22 10:32 UTC, manuio commented on docs/cli.md
> +  -S, --status string          Status query parameter
I agree

2022-08-23 11:24 UTC, dborovcanin commented on docs/cli.md
> +  -S, --status string          Status query parameter
OK, let's proceed this way. In this particular case, use lowercase `user email query parameter` and `user status query parameter`.

2022-08-23 12:26 UTC, dborovcanin commented on docs/cli.md
> +  -S, --status string          Status query parameter
@0x6f736f646f My bad, please capitalize. I thought `string User email query parameter` this is the message, not `User email query parameter`.

2022-08-23 12:30 UTC, 0x6f736f646f commented on docs/cli.md
> +  -S, --status string          Status query parameter
No problem

2022-08-23 13:38 UTC, dborovcanin approved these changes, later dismissed

2022-08-23 13:58 UTC, manuio requested changes

2022-08-23 13:58 UTC, manuio commented on docs/cli.md
> +mainflux-cli channels updatev '{"id":"<channel_id>","name":"myNewName"}' <user_token>
Fix typo `updatev`

2022-08-23 13:58 UTC, manuio commented on docs/api.md
> +
Remove this blank line

2022-08-23 14:16 UTC, 0x6f736f646f commented on docs/cli.md
> +mainflux-cli channels updatev '{"id":"<channel_id>","name":"myNewName"}' <user_token>
It is actually not a typo. I will fix it in both mainflux cli docs and here using this [PR](https://github.com/mainflux/mainflux/pull/1647) https://github.com/mainflux/mainflux/pull/1647

2022-08-23 14:30 UTC, 0x6f736f646f commented on docs/cli.md
> +mainflux-cli channels updatev '{"id":"<channel_id>","name":"myNewName"}' <user_token>
Fixed it in mainflux core repo by this PR https://github.com/mainflux/mainflux/pull/1649

2022-08-23 14:52 UTC, manuio requested changes

2022-08-23 14:52 UTC, manuio commented on docs/cli.md
> +  update       Update channel
Fix the indentation

2022-08-23 14:55 UTC, manuio requested changes

2022-08-23 14:55 UTC, manuio commented on docs/cli.md
remove this blank line

2022-08-23 17:57 UTC, manuio commented on docs/cli.md
> +#### Retrieve All User
Fix `Retrieve All Users` and probably better `Retrieve Users` or `Get Users`. BTW, this is not consistent with `Get Channels` and `Get Things`

2022-08-24 12:26 UTC, 0x6f736f646f commented on docs/cli.md
> +#### Retrieve All User
I will resort to using Get `xxx` as it has been implemented for `api` at https://github.com/mainflux/docs/pull/125

2022-08-24 13:32 UTC, drasko approved these changes
LGTM

2022-08-24 14:00 UTC, dborovcanin approved these changes

2022-08-24 15:04 UTC, merged