NOISSUE - Update docs to include websocket-adapter
absmach/supermq-docs pull request #129
Opened 2022-08-23 14:48 UTC by AryanGodara

Signed-off-by: aryan <aryangodara03@gmail.com>

### What does this do?

### Which issue(s) does this PR fix/relate to?
NOISSUE

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
NO

### Did you document any new/modified functionality?
YES

### Notes
N/A

2022-08-23 20:14 UTC, drasko commented on docs/authentication.md
> +In most of the cases, HTTPS, WSS, MQTTS or secure CoAP are secure enough. However, sometimes you might need an even more secure connection. Mainflux supports mutual TLS authentication (_mTLS_) based
`HTTP, MQTT, WS and MQTT over WS protocols`, but `WS` after `HTTP`, it is more similar to it and belongs there.

2022-08-23 20:14 UTC, drasko commented on docs/messaging.md
> +```javascript
@AryanGodara I guess you tested this example, right?

2022-08-24 05:07 UTC, AryanGodara commented on docs/messaging.md
> +```javascript
I'm still working on this part, there are few typos inside.
I'm thinking of using a golang ws-client instead, I'll commit both, and later remove if it's extra

2022-12-26 09:21 UTC, 0x6f736f646f requested changes

2022-12-26 09:21 UTC, 0x6f736f646f commented on docs/messaging.md
> +	"github.com/gorilla/websocket"
@AryanGodara Can you change the websocket library, it is currently archived by the gorilla team.

2022-12-26 13:01 UTC, AryanGodara commented on docs/messaging.md
> +	"github.com/gorilla/websocket"
https://github.com/ultravioletrs/cocos/issues/67
Issue opened here.
Will wait for some time before updating the ws library.

2022-12-26 17:36 UTC, dborovcanin approved these changes

2022-12-27 02:15 UTC, drasko approved these changes
LGTM

2022-12-27 02:15 UTC, merged