NOISSUE - Add Contenty Type to HTTP Publish Endpoint
absmach/supermq-docs pull request #130
Opened 2022-12-26 10:16 UTC by 0x6f736f646f

### What does this do?
It adds content type json when publishing messages using http endpoint

### Which issue(s) does this PR fix/relate to?
N/A

### List any changes that modify/break current functionality
No

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

#### Before 
```bash
curl -s -S -i -X POST -H "Authorization: Thing 5b5339fc-edff-47e4-a05e-0704fafbacde" http://localhost/http/channels/8448a12c-d5a2-4ba6-bcdd-c8676fa7a36c/messages -d '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]'
HTTP/1.1 415 Unsupported Media Type
Server: nginx/1.20.0
Date: Mon, 26 Dec 2022 09:12:03 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 37
Connection: keep-alive

{"error":"unsupported content type"}
```

#### After
```bash
curl -s -S -i -X POST -H "Content-Type: application/json" -H "Authorization: Thing 5b5339fc-edff-47e4-a05e-0704fafbacde" http://localhost/http/channels/8448a12c-d5a2-4ba6-bcdd-c8676fa7a36c/messages -d '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]'
HTTP/1.1 202 Accepted
Server: nginx/1.20.0
Date: Mon, 26 Dec 2022 09:13:11 GMT
Content-Length: 0
Connection: keep-alive

```

2022-12-26 10:20 UTC, dborovcanin requested changes

2022-12-26 10:20 UTC, dborovcanin commented on docs/messaging.md
> +curl -s -S -i --cacert docker/ssl/certs/ca.crt -X POST -H "Content-Type: application/json" -H "Authorization: Thing <thing_key>" https://localhost/http/channels/<channel_id>/messages -d '[{"bn":"some
The correct type is `application/senml+json`.

2022-12-26 10:34 UTC, dborovcanin approved these changes

2022-12-27 01:37 UTC, drasko approved these changes
LGTM

2022-12-27 01:38 UTC, merged