NOISSUE - Add Groups CLI Documentation
absmach/supermq-docs pull request #132
Opened 2023-01-09 11:06 UTC by rodneyosodo

### What does this do?
Add CLI documentation for groups

### Which issue(s) does this PR fix/relate to?
N/A

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
N/A

2023-01-09 14:56 UTC, drasko submitted a review, later dismissed
LGTM

2023-01-10 10:22 UTC, dborovcanin requested changes

2023-01-10 10:22 UTC, dborovcanin commented on docs/cli.md
> +mainflux-cli groups create '{"Name":<group_name>,"Description":<description>,"ParentID":<parent_id>,"Metadata":<metadata>}' <user_token>
Put placeholders under quotation marks like `"<placeholder>"` to make it valid JSON.

2023-01-10 10:58 UTC, rodneyosodo commented on docs/cli.md
> +mainflux-cli groups create '{"Name":<group_name>,"Description":<description>,"ParentID":<parent_id>,"Metadata":<metadata>}' <user_token>
Done

2023-01-10 13:16 UTC, manuio requested changes

2023-01-10 13:16 UTC, manuio commented on docs/cli.md
> +mainflux-cli bootstrap bootstrap <external_id> <external_key>
Duplication from line 412

2023-01-11 11:28 UTC, rodneyosodo commented on docs/cli.md
> +mainflux-cli bootstrap bootstrap <external_id> <external_key>
Removed

2023-01-11 13:07 UTC, manuio approved these changes
LGTM

2023-01-11 15:46 UTC, drasko approved these changes
LGTM

2023-01-11 16:11 UTC, dborovcanin approved these changes

2023-01-11 16:13 UTC, merged

2023-01-11 16:15 UTC, fbugarski commented
LGTM