NOISSUE - Update Read Messages CLI Documentation
absmach/supermq-docs pull request #134
Opened 2023-01-09 11:08 UTC by rodneyosodo

### What does this do?
Update Read Messages CLI documentation

### Which issue(s) does this PR fix/relate to?
N/A

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
N/A

2023-01-09 12:18 UTC, manuio requested changes

2023-01-09 12:18 UTC, manuio commented on docs/cli.md
> +mainflux-cli messages read <channel_id> <user_token> -R <reader_url>
Is it aligned here: https://github.com/mainflux/mainflux/blob/master/cli/message.go#L28 ?  Looks like we were using Thing Key in the CLI.

2023-01-09 14:52 UTC, drasko requested changes

2023-01-09 14:52 UTC, drasko commented on docs/cli.md
> +mainflux-cli messages read <channel_id> <user_token> -R <reader_url>
I think @mteodor added possibility that both User and THing can read the messages, and we should include both examples.

2023-01-09 16:46 UTC, manuio commented on docs/cli.md
> +mainflux-cli messages read <channel_id> <user_token> -R <reader_url>
Indeed, but this is not aligned with the current CLI

2023-01-10 09:54 UTC, rodneyosodo commented on docs/cli.md
> +mainflux-cli messages read <channel_id> <user_token> -R <reader_url>
[Using the current SDK ](https://github.com/mainflux/mainflux/blob/48e368b59a314e6445ab8460b95981d3f900e1dc/pkg/sdk/go/message.go#L40)we read messages using `<user_token>` rather than `<thing_key>`

Let me send a PR for that

2023-01-10 10:11 UTC, rodneyosodo commented on docs/cli.md
> +mainflux-cli messages read <channel_id> <user_token> -R <reader_url>
@manuio https://github.com/mainflux/mainflux/pull/1696

2023-01-11 12:48 UTC, manuio approved these changes
LGTM

2023-01-11 15:59 UTC, drasko approved these changes
LGTM

2023-01-11 16:10 UTC, dborovcanin approved these changes

2023-01-11 16:10 UTC, merged