NOISSUE - update default service ports
absmach/supermq-docs pull request #136
Opened 2023-03-12 21:06 UTC by SammyOina

### What does this do?
Update service ports in docs for mainflux v0.14
### Which issue(s) does this PR fix/relate to?
Refers to [PR](https://github.com/mainflux/mainflux/pull/1737)

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-03-22 11:47 UTC, dborovcanin commented
Is this one ready? After this one, ofc: https://github.com/mainflux/mainflux/pull/1737

2023-03-22 13:46 UTC, SammyOina commented
> Is this one ready? After this one, ofc: [mainflux/mainflux#1737](https://github.com/mainflux/mainflux/pull/1737)

@dborovcanin Yes, this ready for review, but I'll move it from draft once [mainflux/mainflux#1737](https://github.com/mainflux/mainflux/pull/1737) is merged

2023-04-03 11:16 UTC, dborovcanin submitted a review, later dismissed

2023-04-03 11:17 UTC, dborovcanin commented
We need updates on [Devops repo](https://github.com/mainflux/devops/pulls) before merging this one.

2023-04-04 10:22 UTC, rodneyosodo requested changes
update:
- [ ] docs/bootstrap.md
- [ ] docs/edge.md
- [ ] docs/storage.md
- [ ] docs/twins.md

2023-04-05 07:45 UTC, SammyOina commented
> We need updates on [Devops repo](https://github.com/mainflux/devops/pulls) before merging this one.

PR open [here](https://github.com/mainflux/devops/pull/123)

2023-04-06 07:23 UTC, rodneyosodo requested changes
Update `docs/messaging.md`

2023-04-13 10:35 UTC, dborovcanin submitted a review, later dismissed

2023-04-13 12:31 UTC, rodneyosodo requested changes
Change `localhost:8204` in `docs/provision.md`
also in  `docs/storage.md`

2023-04-13 13:15 UTC, rodneyosodo commented on docs/storage.md
> +http://localhost:8008/channels/<channelID>/messages/home/temperature/myFormat
```suggestion
http://localhost:<service_port>/channels/<channelID>/messages/home/temperature/myFormat
```

2023-04-13 13:28 UTC, rodneyosodo commented on docs/storage.md
> +```bas8202h
```suggestion
```bash
```

2023-04-13 13:31 UTC, rodneyosodo commented on docs/storage.md
> +- 3001 by Grafana
This was removed by https://github.com/mainflux/docs/pull/139

2023-04-13 13:32 UTC, rodneyosodo commented on docs/storage.md
> +- 3001 by Grafana
```suggestion
```

2023-04-13 13:41 UTC, rodneyosodo approved these changes

2023-04-13 14:05 UTC, drasko approved these changes
LGTM

2023-04-17 15:22 UTC, dborovcanin approved these changes

2023-04-17 15:22 UTC, merged