NOISSUE - Add Requirements File
absmach/supermq-docs pull request #137
Opened 2023-04-03 10:24 UTC by rodneyosodo

### What does this do?
Adds a requirement file to be able to install a specific version of `mkdocs` that runs well. When the version isn't set `mkdocs` fails as the latest jinja version breaks serving docs locally.

### Which issue(s) does this PR fix/relate to?
NOISSUE

### List any changes that modify/break current functionality
Introduces a requirements file to be able to install a specific version of mkdocs and jinja that works

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
References https://github.com/mkdocs/mkdocs/issues/2799

2023-04-13 14:07 UTC, drasko requested changes
Why all of this? Isn't `pip` supposed to pull and install all the dependencies for `mkdocs`?

2023-04-13 17:57 UTC, rodneyosodo commented
> Why all of this? Isn't `pip` supposed to pull and install all the dependencies for `mkdocs`?

We aren't changing from `pip`. We will still be using `pip`. Since the `jinja2` 3.1.0 release `mkdocs` does not work. If you have previous version of `jinja` it will work. Moving to a requirements files makes have the specific version of `mkdocs` and `jinja` that work.

2023-05-15 08:39 UTC, dborovcanin approved these changes, later dismissed

2023-05-23 07:28 UTC, SammyOina requested changes

2023-05-23 07:28 UTC, SammyOina commented on requirements.txt
> +mkdocs==1.4.2
```suggestion
mkdocs==1.4.2
mkdocs-material==9.1.14
```

2023-06-14 10:48 UTC, drasko commented
@rodneyosodo please update this one and address the comments if needed.

2023-06-14 10:59 UTC, dborovcanin commented on requirements.txt
> +mkdocs==1.4.2
@rodneyosodo What about this suggestion?

2023-06-14 11:18 UTC, rodneyosodo commented on requirements.txt
> +mkdocs==1.4.2
It works without `mkdocs-material`

2023-06-14 11:30 UTC, dborovcanin submitted a review, later dismissed

2023-06-16 11:33 UTC, drasko requested changes

2023-06-16 11:33 UTC, drasko commented on README.md
> +pip install -r requirements.txt
What are there requirements for? These are normally for MkDocs, and are automatically pulled by `pip`.

2023-06-16 11:35 UTC, SammyOina commented on requirements.txt
> +mkdocs==1.4.2
I got an error for missing the dependency, it might not work for all environements

2023-06-22 21:31 UTC, drasko commented on README.md
> +pip install -r requirements.txt
@rodneyosodo ^

2023-06-26 15:33 UTC, rodneyosodo commented on README.md
> +pip install -r requirements.txt
The requirements file is a lock file for the specific version of dependencies for example `go.mod` file. When `Jinja2==3.1.0` was the latest release it had problems with `mkdocs` that is why I am suggesting a requirements file that locks the `mkdocs` version with a specific version of `Jinja` that works. The other alternative will be to install a specific version of `mkdocs` for example:
```bash
pip install mkdocs==1.4.3
```

2023-06-26 15:35 UTC, drasko commented on README.md
> +pip install -r requirements.txt
I would just make it sure that everything works with latest `mkdoc`, and leave to user to debug if he/she cannot figure out to install most recent version.

2023-06-27 14:05 UTC, rodneyosodo commented on requirements.txt
> +mkdocs==1.4.2
What is your environment, because it works without on my side?

[![asciicast](https://asciinema.org/a/593519.svg)](https://asciinema.org/a/593519)

2023-07-26 10:55 UTC, SammyOina approved these changes

2023-07-26 13:58 UTC, rodneyosodo commented
Closing this because of https://github.com/mainflux/docs/pull/137#discussion_r1242385976

2023-07-26 13:58 UTC, closed without merging