NOISSUE- Clients Integration
absmach/supermq-docs pull request #138
Opened 2023-04-04 20:33 UTC by rodneyosodo

Signed-off-by: rodneyosodo <blackd0t@protonmail.com>

### What does this do?
Add documentation for clients integration

### Which issue(s) does this PR fix/relate to?
NOISSUE

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
Yes

### Notes
To be merged after

2023-04-04 20:59 UTC, drasko requested changes

2023-04-04 20:59 UTC, drasko commented on docs/authentication.md
> +There is one two types of authentication keys:
one or two?

2023-04-06 11:23 UTC, rodneyosodo commented on docs/authentication.md
> +There is one two types of authentication keys:
two

2023-06-14 10:47 UTC, drasko commented
@rodneyosodo please resolve conflicts

2023-06-14 12:44 UTC, drasko approved these changes
LGTM

2023-06-14 12:44 UTC, merged