NOISSUE - Update Examples
absmach/supermq-docs pull request #146
Opened 2023-06-26 15:18 UTC by rodneyosodo

Signed-off-by: rodneyosodo <blackd0t@protonmail.com>

### What does this do?
- Update the examples with the latest changes in master
- Rearrange links to be at the bottom of the page
- Increase clarification on policies
- Fixes on `group` members as for `things groups` i.e `channels` a `user` or a `thing` maybe connected to it

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
- Updates the examples on documentation
- Removes repetitive API docs from `clients.md`

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
Reflects latest changes on https://github.com/mainflux/mainflux/tree/master and https://github.com/mainflux/mainflux/pull/1831

2023-06-27 12:10 UTC, SammyOina approved these changes

2023-07-19 14:45 UTC, ianmuchyri commented on docs/authorization.md
> +**g\_** Policy represents the client's rights to modify the group/channel itself. Only group/channel members with correct rights can modify or update the group/channel, or add/remove members to/from
```suggestion
**g\_** Policy represents the client's rights to modify the group/channel itself. Only group/channel members with correct rights can modify or update the group/channel, or add/remove members to/from the group. **g_add**, **g_list**, **g_update** and **g_delete** are the only supported actions. With **g_add** the client can add members to the group/channel. With **g_list** the client can list the group/channel and its members. With **g_update** the client can update the group/channel. With **g_delete** the client can delete the group/channel.
```

2023-07-19 14:45 UTC, ianmuchyri commented on docs/authorization.md
> +Finally, the **c\_** policy represents the rights the member has over other members of the group/channel. Only group/channel members with correct rights can modify or update other members of the grou
```suggestion
Finally, the **c\_** policy represents the rights the member has over other members of the group/channel. Only group/channel members with correct rights can modify or update other members of the group/channel. **c_list**, **c_update**, **c_share** and **c_delete** are the only supported actions. With **c_list** the client can list the group/channel and other members of the group/channel. With **c_update** the client can update other members of the group/channel. With **c_share** the client can share the group/channel with other clients. With **c_delete** the client can delete other members of the group/channel.
```

2023-07-19 14:45 UTC, ianmuchyri commented on docs/authorization.md
> +By default, mainflux adds listing action to **c\_** and **g\_** policies. This means that all members of the group/channel can list the group/channel or its members. When adding a new member to a gro
The use of or is a little confusing. I'm not sure exactly what you meant but the use of and is better as with the case of c_list you see the group and its members, with or you imply its either not both

2023-07-19 14:48 UTC, rodneyosodo commented on docs/authorization.md
> +**g\_** Policy represents the client's rights to modify the group/channel itself. Only group/channel members with correct rights can modify or update the group/channel, or add/remove members to/from
It is an `or` operation. You don't list them together

2023-07-19 14:49 UTC, rodneyosodo commented on docs/authorization.md
> +Finally, the **c\_** policy represents the rights the member has over other members of the group/channel. Only group/channel members with correct rights can modify or update other members of the grou
It is an `or` operation. You don't list them together

2023-07-19 15:02 UTC, ianmuchyri commented on docs/authorization.md
> +**g\_** Policy represents the client's rights to modify the group/channel itself. Only group/channel members with correct rights can modify or update the group/channel, or add/remove members to/from
Having `or` implies that I can only do one of the actions not both. I get that they are done separately but using or here implies if I can list group/channel I cannot list members and viceversa

2023-07-28 09:44 UTC, darkodraskovic requested changes

2023-07-28 09:44 UTC, darkodraskovic commented on docs/architecture.md
> +| [mainflux-cli][mainflux-cli]   | Command line interface                                                                  |
Do we need to repeat `communication` when we're talking about channels?

2023-07-28 09:44 UTC, darkodraskovic commented on docs/architecture.md
> +`User` represents the real (human) user of the system. They are represented via their identity, email address, and secret, password, which they use as platform access credentials in order to obtain a
In the first sentence, you use singular for "user". In the second sentence, you say, they are. So there's an inconsistency there. I would start the second sentence with, "Users are". Also, I was a bit confused when reading the second sentence, I did not know if identity and email address are two separate things, the same goes for secret and password. I would say rather something like, represented via their email address, used as their identity, and password, used as their secret".

2023-07-28 09:44 UTC, darkodraskovic commented on docs/architecture.md
> +`Group` represents a logical group of users. It is used to simplify access control management by allowing users to be grouped together. A user is grouped by assigning them to a group with specified p
"logical groupping".

"by assigning them to a group with specified policies" - does the assignment to a group happens by using policy or we assign a user to a group that already has some policy attached to it? It's ambiguos. Try to be more clear and precise here.

"as long as"

"Users in one group have access to other users in the same group so long as they have the required policy" - so I can belong to a group without having a policy attached to a group? 

I would try to be more elaborate in this paragraph, since you introduce some ideas about group mechanics. Try to be as clear and as precise as possible

2023-07-28 09:44 UTC, darkodraskovic commented on docs/architecture.md
> +`Channel` represents a communication channel. It serves as message topic that can be consumed by all of the things connected to it. It also servers a grouping mechanism for things. A thing can be con
"serves as a message topic"

"serves as a grouping mechanism"

"to have an access to the messages"

"and also things connected to that channel with the required policy" - who has thep policy? Users or things?

2023-07-28 09:44 UTC, darkodraskovic commented on docs/architecture.md
> +Running Mainflux on gateway moves computation from cloud towards the edge thus decentralizing IoT system. Since we can deploy same Mainflux code on gateway and in the cloud there are many benefits bu
"they will have the same known work" - there's something wrong with this sentence.

2023-08-06 11:51 UTC, drasko commented
@rodneyosodo please proceed with this with the highest priority, so that we can merge it and not block the others to write additional documentation.

2023-08-08 07:24 UTC, rodneyosodo commented on docs/architecture.md
> +| [mainflux-cli][mainflux-cli]   | Command line interface                                                                  |
I think so, because they are adapters and basically function the same. I have rephrased to `for sending and receiving messages via`

2023-08-08 07:31 UTC, rodneyosodo commented on docs/architecture.md
> +`Group` represents a logical group of users. It is used to simplify access control management by allowing users to be grouped together. A user is grouped by assigning them to a group with specified p
> so I can belong to a group without having a policy attached to a group?

No. Assigning a user to a group is the same as creating a policy

2023-08-08 12:19 UTC, darkodraskovic requested changes

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +curl -sSiX POST http://localhost/users -H "Content-Type: application/json" -H "Authorization: Bearer [user_token]" -d @- << EOF
Use `<>` for non optional stuff, like `user_token` here.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +EOF
If you include `tags`, for example, can it have `[]` as a value, i.e. can it have an empty array? If not, than at least the first item is non optional.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +You can also use `[user_token]` so that the owner of the new user is the one identified by the `[user_token]` for example:
Why do you use `[]` here?

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +You can get all users in the database by querying this endpoint.
Since this is a new paragraph, the word `this` should be replaced by the literal value reference, `/users`, in this case.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +curl -sSiX GET http://localhost/users?offset=[offset]&limit=[limit]&identity=[identity] -H "Authorization: Bearer <user_token>"
if you already have an `offset` key, then the `limit` value is not optional.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +You can get all groups a user is assigned to by calling the get user memberships function.
Use GET for HTTP methods. Btw, it's not a function, it's a method (terminologywise).

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +If you want to paginate your results then use this `offset`, `limit`, `metadata`, `name`, `status`, `parentID`, `ownerID`, `tree` and `dir` query parameters.
You don't need "this". Propagate this all over the docs.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +> Must take into consideration the user identified by the `user_token` needs to be assigned to the same group with `c_list` action or is the owner of the user identified by the `user_id`.
There's something grammatically wrong with this sentence.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +EOF
These are all optional? Even `id`?

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +To create a thing with an external ID, you need provide the ID together with thing name, and other fields as well as a `user_token`
"to provide"

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +It is often the case that the user will want to integrate the existing solutions, e.g. an asset management system, with the Mainflux platform. To simplify the integration between the systems and avoi
There's something grammatically wrong with "while create the Thing".

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +To create a thing with an external secret, you need provide the secret together with thing name, and other fields as well as a `user_token`
"to provide" after "need".

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +EOF
Can you use some meaningful and realistic values here?

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +EOF
You use underscores for blanks in placeholder elsewhere. If that's a convention, use them all over the docs consistently.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +EOF
Use multiple tags to signal the array, and also use meaningful and realistic tags.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +If you want to paginate your results then use this `offset`, `limit`, `metadata`, `name`, `status`, `parentID`, `ownerID`, `tree` and `dir` query parameters.
Again, no need for "this" here.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +> `actions` is optional, if not provided, the default action is `m_read` and `m_write`.
"the default actions are"?

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +EOF
If these are arrays, please put multiple placeholders to signal that. In that case, the first one should be in `<>` and the rest of the stuff in `[]`.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +> `actions` is optional, if not provided, the default action is `m_read` and `m_write`.
"the default actions are"?

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +EOF
This is not an example. Use placeholder values and `[]`/`<>` according to the value case.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +EOF
Underscores? Or if it's not a contrived example, maybe not.

2023-08-08 12:19 UTC, darkodraskovic commented on docs/api.md
> +You can get all groups for a logged in user.
"logged-in"? Please check on this and propagate it all over.

2023-08-08 14:19 UTC, rodneyosodo commented on docs/api.md
> +curl -sSiX POST http://localhost/users -H "Content-Type: application/json" -H "Authorization: Bearer [user_token]" -d @- << EOF
It is optional

2023-08-08 14:22 UTC, rodneyosodo commented on docs/api.md
> +EOF
Yes, it can have `[]` as a value.

2023-08-08 14:33 UTC, rodneyosodo commented on docs/api.md
> +curl -sSiX GET http://localhost/users?offset=[offset]&limit=[limit]&identity=[identity] -H "Authorization: Bearer <user_token>"
no. If it is not specified it will default to `10`

2023-08-08 14:36 UTC, rodneyosodo commented on docs/api.md
> +EOF
Yes

2023-08-09 09:16 UTC, darkodraskovic requested changes

2023-08-09 09:16 UTC, darkodraskovic commented on docs/api.md
> +curl -sSiX POST http://localhost/users -H "Content-Type: application/json" -H "Authorization: Bearer [user_token]" -d @- << EOF
`[user_token]` this is optional?

2023-08-09 09:16 UTC, darkodraskovic commented on docs/api.md
> +curl -sSiX GET http://localhost/users?offset=[offset]&limit=[limit]&identity=[identity] -H "Authorization: Bearer <user_token>"
However, if you do like so `offset=&limit=&identity=087054dc-368f-11ee-be56-0242ac120002`, this will create an error.

The correct syntax should be `[offset=<offset>]`. Here, the whole construct is optional, but once you have `offset=` you must have offset value.

2023-08-09 09:16 UTC, darkodraskovic commented on docs/api.md
> +curl -sSiX POST http://localhost/users -H "Content-Type: application/json" -H "Authorization: Bearer [user_token]" -d @- << EOF
If it is, the correct syntax is `["Authorization: Bearer <user_token>"]`.

2023-08-09 09:16 UTC, darkodraskovic commented on docs/api.md
> +> `actions` is optional, if not provided, the default action is `m_read` and `m_write`.
I don't see his addressed. Should be, the default actions are `m_read` and `m_write`

2023-08-09 09:33 UTC, rodneyosodo commented on docs/api.md
> +curl -sSiX GET http://localhost/users?offset=[offset]&limit=[limit]&identity=[identity] -H "Authorization: Bearer <user_token>"
Aah. I see

2023-08-09 09:42 UTC, rodneyosodo commented on docs/api.md
> +EOF
It is the json tag for parent ID

2023-08-09 09:43 UTC, rodneyosodo commented on docs/api.md
> +EOF
This is an example of a name. I have change it to be realtistic i.e `Pressure Sensor`

2023-08-09 15:41 UTC, drasko approved these changes
LGTM

2023-08-09 15:41 UTC, merged