NOISSUE - Update edge docuementation
absmach/supermq-docs pull request #152
Opened 2023-07-26 09:51 UTC by SammyOina

### What does this do?
updates export test example

### Which issue(s) does this PR fix/relate to?
Relates to https://github.com/mainflux/export/pull/37 and https://github.com/mainflux/agent/pull/56

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-07-26 14:01 UTC, rodneyosodo commented
Can this be changed to draft up until https://github.com/mainflux/export/pull/37 and https://github.com/mainflux/agent/pull/56 are merged or add `DRAFT - ` prefix

2023-07-28 14:05 UTC, rodneyosodo approved these changes

2023-07-28 15:27 UTC, drasko requested changes

2023-07-28 15:27 UTC, drasko commented on docs/edge.md
> +go run -tags nats ./examples/publish/main.go -s http://localhost:4222 export.test "[{\"bn\":\"test\"}]";
Why do we need tag here?

2023-07-28 16:05 UTC, SammyOina commented on docs/edge.md
> +go run -tags nats ./examples/publish/main.go -s http://localhost:4222 export.test "[{\"bn\":\"test\"}]";
We don't have to put it but for documentation reasons, it is good to have it Incase one may want to use rabbitmq

2023-08-01 13:15 UTC, drasko requested changes

2023-08-01 13:15 UTC, drasko commented on docs/edge.md
> +go run -tags nats ./examples/publish/main.go -s http://localhost:4222 export.test "[{\"bn\":\"test\"}]";
Please do not put it like this, leave default command, and then belove explain how one can use alternative (for example in the note below, you can say: "This will ran NATS broker by default, if you want Rabbit, use this tag ..." - something like this).

2023-08-01 15:43 UTC, drasko requested changes

2023-08-01 15:43 UTC, drasko commented on docs/edge.md
> +We have configured route for export, `nats_topic = ">"` means that it will listen to `NATS` subject `export.>` and `mqtt_topic` is configured so that data will be sent to MQTT broker on topic `channe
Is this different build for different brokers documented somewhere (maybe in `Developer's guide`)? If not, please add it in the appropriate section, and refer here (with link) to this detailed explanation.

2023-08-01 19:07 UTC, SammyOina commented on docs/edge.md
> +We have configured route for export, `nats_topic = ">"` means that it will listen to `NATS` subject `export.>` and `mqtt_topic` is configured so that data will be sent to MQTT broker on topic `channe
I have added some more information to the dev guide and linked to it from here

2023-08-01 19:40 UTC, drasko approved these changes
LGTM

2023-08-01 19:41 UTC, merged