Noissue - Add config docs
absmach/supermq-docs pull request #154
Opened 2023-08-06 12:01 UTC by WashingtonKK

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Adds documentation for CLI Config command

### Which issue(s) does this PR fix/relate to?
NOISSUE

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes
To be merged after https://github.com/mainflux/mainflux/pull/1858

2023-08-14 05:52 UTC, SammyOina requested changes

2023-08-14 05:52 UTC, SammyOina commented on docs/cli.md
> +#### Get Memberships
are the changes for groups missing or meant to be in this PR

2023-08-14 08:07 UTC, SammyOina commented
use rebase rather than merge
![image](https://github.com/mainflux/docs/assets/44265300/a7a61755-76ad-4cc4-a641-cffe516b8d71)

`git config pull.rebase true`

2023-08-14 08:09 UTC, ianmuchyri commented on docs/cli.md
> +mainflux-cli groups assign <member_ids> <member_type> <group_id> <user_token>
check on the new updates on` mainflux-cli assign`

2023-08-14 08:09 UTC, WashingtonKK commented on docs/cli.md
> +#### Get Memberships
I have removed them, it was an error.

2023-08-14 08:11 UTC, WashingtonKK commented on docs/cli.md
> +mainflux-cli groups assign <member_ids> <member_type> <group_id> <user_token>
Okay

2023-08-14 08:11 UTC, WashingtonKK commented on docs/cli.md
> +mainflux-cli groups assign <member_ids> <member_type> <group_id> <user_token>
Is that going to be in this PR?

2023-08-14 08:11 UTC, ianmuchyri commented on docs/cli.md
> +```
add the other `get` commands: `children` and `parents`

2023-08-14 08:11 UTC, WashingtonKK commented on docs/cli.md
> +mainflux-cli groups assign <member_ids> <member_type> <group_id> <user_token>
@ianmuchyri

2023-08-14 08:12 UTC, ianmuchyri commented on docs/cli.md
> +```
also, add the` update` command to update a group's details

2023-08-14 08:12 UTC, WashingtonKK commented on docs/cli.md
> +```
Is this supposed to be in this PR? @ianmuchyri, or this one is just to add cli config  docs

2023-08-14 08:14 UTC, ianmuchyri commented on docs/cli.md
> +```
Oh, yeah, you can create another pr on that

2023-08-14 08:14 UTC, ianmuchyri commented on docs/cli.md
> +```
I hadn't seen you had removed them

2023-08-14 08:14 UTC, ianmuchyri commented on docs/cli.md
> +mainflux-cli groups assign <member_ids> <member_type> <group_id> <user_token>
On another. You can resolve this comment

2023-08-14 08:14 UTC, ianmuchyri commented on docs/cli.md
> +```
On another. You can resolve this comment

2023-08-14 09:18 UTC, dborovcanin requested changes

2023-08-14 09:18 UTC, dborovcanin commented on docs/cli.md
> +This command is used to set the flags to be used by CLI in a local TOML file. The default location of the TOML file is near the binaries. To change the location of the TOML file you can run the comma
`The default location of the TOML file is near the binaries` -> `is in the same directory as the CLI binary`

2023-08-14 09:18 UTC, dborovcanin commented on docs/cli.md
> +## Config
Add some explanation here, like:
Mainflux CLI tool supports configuration files that contain some of the basic settings so you don't have to specify them through flags.

2023-08-14 09:43 UTC, dborovcanin submitted a review, later dismissed

2023-08-14 10:08 UTC, SammyOina approved these changes

2023-08-17 12:54 UTC, drasko requested changes

2023-08-17 12:54 UTC, drasko commented on docs/cli.md
> +  - bootstrap_url
Kill this space between `-` and the option

2023-08-22 12:55 UTC, drasko requested changes

2023-08-22 12:55 UTC, drasko commented on docs/cli.md
> +  -bootstrap_url
Kill empty space behind the string. Add description like for any Linux tool.

2023-08-22 12:55 UTC, drasko commented on docs/cli.md
> +  -bootstrap_url
Add a table with description

2023-08-22 15:42 UTC, WashingtonKK commented on docs/cli.md
> +  -bootstrap_url
Okay

2023-08-25 14:18 UTC, drasko approved these changes
LGTM

2023-08-25 14:18 UTC, merged