NOISSUE - Enhance opcua docs
absmach/supermq-docs pull request #155
Opened 2023-08-21 05:57 UTC by WashingtonKK

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Enhances the OPC-UA docs and adds an illustration of how it can be used.

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)
None

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-10-03 14:52 UTC, dborovcanin reviewed
@WashingtonKK Can you align the look and feel of the diagram with other diagrams in the docs?

2023-10-20 20:56 UTC, drasko requested changes

2023-10-20 20:56 UTC, drasko commented on docs/opcua.md
> +|       ![OPC-UA][opcua-diagram]        |
PLease align this nicely, killing the extra space on the right side

2024-03-05 22:31 UTC, drasko commented
@WashingtonKK please fix this diagram so that we can move on. @SammyOina please review this PR.

2024-03-06 08:36 UTC, WashingtonKK commented
@drasko , I updated the image. Now I'm waiting for remarks on the image and the PR

2024-05-17 14:57 UTC, dborovcanin approved these changes

2024-05-17 14:58 UTC, merged