NOISSUE - Add Kafka Architectural Docs
absmach/supermq-docs pull request #157
Opened 2023-08-29 10:20 UTC by rodneyosodo

Signed-off-by: Rodney Osodo <socials@rodneyosodo.com>

### What does this do?
Add documentation on how mainflux utilizes kafka to pubsub

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
To be merged after https://github.com/mainflux/docs/pull/156 and https://github.com/mainflux/mainflux/pull/1579

2023-09-14 14:10 UTC, dborovcanin requested changes

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +Mainflux has one exchange for the entire platform called `mainflux`. This exchange is of type `topic`. The exchange is `durable` i.e it will survive broker restarts and remain declared when there are
...i.e. it will survive (missing dot)...
..published to by other... -> accessed by; other exchanges can publish to it.

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +Mainflux uses topic based routing to route messages to the appropriate queues. The routing key is in the format `channels.<channel_id>.<optional_subtopic>`. A few valid routing key examples: `channel
topic-based routing

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +The amqp published message doesn't contain any headers. The message body is the payload of the message.
AMQP

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +Mainflux supports MQTT protocol for message exchange. MQTT is extremely simple and lightweight Publish/Subscribe messaging protocol used to connect restricted devices in low bandwidth, high-latency o
MQTT is a lightweight...

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +To enable MQTT support on NATS, jestream needs to be enabled. This is done by default in mainflux. This is because persistence is necessary for sessions and retained messages, even for QoS 0 retained
...JetStream (capital) needs to be enabled.

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +Since mainfux supports configurable message broker, you can use Nats with Jestream enabled as a message broker. To do so, you need to set `MF_BROKER_TYPE` to `nats` and set `MF_NATS_URL` to the url o
Since Mainflux...

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +Since mainflux is using `nats:2.9.21-alpine` docker image with the following configuration:
The same. Check for others.

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +VerneMQ uses a master-less clustering technology, which means there are no special nodes like masters or slaves to consider when adding or removing nodes, making cluster operation safe and simple. Th
Thsi -> this

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +- Full MQTT Support: VerneMQ implements the full MQTT 3.1, 3.1.1, and 5.0 specifications, including various QoS levels, authentication and authorization options, TLS/SSL encryption, websockets suppor
WebSockets

2023-09-14 14:10 UTC, dborovcanin commented on docs/messaging.md
> +NATS support upto QoS 1 subscriptions, where the server retains messages until it receives the PUBACK for the corresponding packet identifier. If PUBACK is not received within the "ack_wait" interval
NATS supports up to

2023-10-20 20:56 UTC, drasko approved these changes
LGTM

2023-10-20 21:00 UTC, merged