MF-162 - ES With NATS JetStream
absmach/supermq-docs pull request #164
Opened 2023-10-05 16:36 UTC by Musilah

### What does this do?
Add Nats Jetstream Event Sourcing Documentation to the Docs. 
### Which issue(s) does this PR fix/relate to?
 Resolves #162

### List any changes that modify/break current functionality
None
### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
Yes.
### Notes

2023-10-20 20:53 UTC, drasko submitted a review, later dismissed
This is OK for me. @rodneyosodo @dborovcanin and @SammyOina please review.

2024-01-25 14:09 UTC, dborovcanin requested changes

2024-01-25 14:09 UTC, dborovcanin commented on docs/events.md
> +    ```nats
Use `bash` or `json`.

2024-01-25 14:09 UTC, dborovcanin commented on docs/events.md
> +    ```
Use ```json.

2024-01-25 14:09 UTC, dborovcanin commented on docs/events.md
> +    ```nats
Do that for all the other cases.

2024-01-28 22:26 UTC, rodneyosodo requested changes

2024-01-28 22:26 UTC, rodneyosodo commented on docs/events.md
> +[mf-docker-compose]: https://github.com/mainflux/mainflux/blob/master/docker/docker-compose.yml
Change the URLs

2024-01-31 17:12 UTC, dborovcanin approved these changes

2024-01-31 17:12 UTC, merged