NOISSUE - Docs for domains , groups, channel, things relationship
absmach/supermq-docs pull request #174
Opened 2024-02-05 15:34 UTC by arvindh123

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Docs for domains , groups, channel, things relationship with details and diagram

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2024-02-13 10:34 UTC, dborovcanin requested changes

2024-02-13 10:34 UTC, dborovcanin commented on docs/authorization.md
> +Domain hold all entities such as Groups, Channels and Things.
...holds entities (not all, e.g. Users).

2024-02-13 10:34 UTC, dborovcanin commented on docs/authorization.md
> +The entities created in Domain doesn't creates have hierarchical structure within domain.
This is confusing, please fix it.

2024-02-13 10:34 UTC, dborovcanin commented on docs/authorization.md
> +Example: In Domain_1 a user creates following entities Group 1, Group_2, Thing 1, Thing 2, Channel 1, Channel 2. By default their will be relation betweens the entities, until user assigns relation b
`By default their will be relation betweens the entities, until user assigns relation between entities` What does it mean: Will there be an implicit relation or not?

2024-02-13 10:34 UTC, dborovcanin commented on docs/authorization.md
> +`Thing` represents devices (or applications) connected to Magistrala that uses the platform for message exchange with other `things`.
...a device (or an application)...

2024-02-13 10:34 UTC, dborovcanin commented on docs/authorization.md
> +`Channel` represents a communication channel. It serves as message topic that can be consumed by all of the things connected to it.
... as a message conduit between things connected to it.

2024-02-13 10:34 UTC, dborovcanin commented on docs/authorization.md
> +To Channel communication topics things can publish/Subscribe the messages.
Things can publish or subscribe to the channel.

2024-02-13 10:34 UTC, dborovcanin commented on docs/authorization.md
> +Groups are entities that can be linked as parents to channels.
Explain (what does parent mean, how does hierarchy work, can there be multiple ancestors...).

2024-03-05 11:29 UTC, rodneyosodo requested changes

2024-03-05 11:29 UTC, rodneyosodo commented on docs/authorization.md
> +Domain contains **Things**, **Channels**, and **Groups**. **Users** can be a member of a Domain with different types of available relations, These relation provides access control to the entities in
```suggestion
Domain contains **Things**, **Channels**, and **Groups**. A **User** can be a member of a Domain with different types of available relations, These relation provides access control to the entities in the domain.
```

2024-03-05 11:29 UTC, rodneyosodo commented on docs/authorization.md
> +The entities created in Domain don't have any hierarchical structure between them.
```suggestion
The entities created in a domain don't have any hierarchical structure between them.
```

2024-03-05 11:29 UTC, rodneyosodo commented on docs/authorization.md
> +Example: In Domain_1 a user creates the following entities Group 1, Group_2, Thing 1, Thing 2, Channel 1, Channel 2. By default, there is no relation between the entities, until the user assigns a re
Let's be consistent with naming i.e either use snake case every where.
```suggestion
Example: In domain_1 a user creates the following entities group_1, group_2, thing_1, thing_2, channel_1, channel_2. By default, there is no relation between the entities, until the user assigns a relation between the entities
```

Reword the second line because when creating an entity we add a policy hence there is a relation between the entity and the user.

2024-03-05 11:29 UTC, rodneyosodo commented on docs/authorization.md
> +`Thing` represents a device (or applications) connected to Magistrala that uses the platform for message exchange with other `things`.
```suggestion
`Thing` represents a device (or an application) connected to Magistrala that uses the platform for message exchange with other `things`.
```

2024-03-05 11:29 UTC, rodneyosodo commented on docs/authorization.md
> +curl --location 'http://localhost/connect' \
Use same structure as used in the API docs

```sh
curl -sSiX POST http://localhost/connect -H "Content-Type: application/json" -H "Authorization: Bearer <domain_user_access_token>" -d @- << EOF
{
  "thing_id": "<Thing 1 ID>",
  "channel_id": "<Channel 1 ID>"
}
EOF
```

2024-03-05 11:29 UTC, rodneyosodo commented on docs/authorization.md
> +_*The below diagram shows Thing 1 connect to channel 1 , channel 2 and Thing 2 connect to Thing 2. This relationship can be established using the provided request*_
```suggestion
_*The below diagram shows Thing 1 is connected to channel 1 and channel 2 and Thing 2 is connected to Channel 2. This relationship can be established using the provided request*_
```

Also there is no provided request

2024-03-05 11:49 UTC, rodneyosodo requested changes

2024-03-05 11:49 UTC, rodneyosodo commented on docs/authorization.md
> +A Group serves as a parent entity that can contain both child Groups and Channels. Child Groups, in turn, can consist of further child Groups or Channels, forming a nested hierarchy. Notably, Channel
```suggestion
A Group serves as a parent entity that can contain both groups and channels as children.
```
Same as other cases

2024-03-05 11:49 UTC, rodneyosodo commented on docs/authorization.md
> +```bash
same

2024-03-05 11:49 UTC, rodneyosodo commented on docs/authorization.md
> +_*The diagram below illustrates the parent relationship between Channel 1 and Channel 2 with Group 2. This relationship can be established using the provided request.*_
same

2024-03-05 14:07 UTC, arvindh123 commented on docs/authorization.md
> +_*The below diagram shows Thing 1 connect to channel 1 , channel 2 and Thing 2 connect to Thing 2. This relationship can be established using the provided request*_
Starting part of document explain about the hierarchy, Assign and unassign of entities are explained in later part of document

2024-03-05 14:14 UTC, arvindh123 commented on docs/authorization.md
> +Example: In Domain_1 a user creates the following entities Group 1, Group_2, Thing 1, Thing 2, Channel 1, Channel 2. By default, there is no relation between the entities, until the user assigns a re
Yes, While creating an entity there will be relation between entity and user. 
But here the case different, We want to explain to reader about relation between a entity with other entities. 
Since this part of document explain about entity relationship, and didn't mentioned about user entity relation. 
User entity relation in explained in detail in following parts of documents.

2024-03-06 08:36 UTC, rodneyosodo requested changes
Also check for capital letters. Is there are reason why some names are capitalized yet they don't start the sentence for example

- `**user_3 Request for Connect thing_101 & channel_101:**` Request and Connect are capitalized
- `Domain holds entities such as Groups, Channels, and Things.` Groups are capitalized yet further in the docs there are some cases where Groups is not capitalized
- `When Domain Member user_4 becomes an Administrator of group_101, user_4 can able to update, delete, assign, and unassign to group_101. Since group_101 has channel_101 and thing_101 as children. The user_5 has Administrator access on group_101 child entities channel_101 and thing_101.` For example, Domain and Member are capitalized.

2024-03-06 08:36 UTC, rodneyosodo commented on docs/authorization.md
> +Domain contains **Things**, **Channels**, and **Groups**. A **User** can be a member of a Domain with different types of available relations, These relation provides access control to the entities in
```suggestion
Domain contains **Things**, **Channels**, and **Groups**. A **User** can be a member of a Domain with different types of available relations. This relation provides access control to the entities in the domain.
```

2024-03-06 08:36 UTC, rodneyosodo commented on docs/authorization.md
> +Example: In domain_1 a user creates the following entities `group_1`, `group_2`, `thing_1`, `thing_2`, `channel_1`, `channel_2`. By default, there is no relation between the entities, until the user
```suggestion
Example: In `domain_1` a user creates the following entities `group_1`, `group_2`, `thing_1`, `thing_2`, `channel_1`, `channel_2`. By default, there is no relation between the entities, until the user assigns a relation between the entities
```

2024-03-06 08:36 UTC, rodneyosodo commented on docs/authorization.md
> +`Thing` represents a device (or an application) connected to Magistrala that uses the platform for message exchange with other `things`.
Also update the documentation here  https://docs.magistrala.abstractmachines.fr/entities/#things-service

2024-03-07 12:54 UTC, rodneyosodo approved these changes, later dismissed

2024-03-20 15:37 UTC, dborovcanin requested changes

2024-03-20 15:37 UTC, dborovcanin commented on docs/authorization.md
> +A group serves as a parent entity that can contain both groups and channels as children. Child groups, in turn, can consist of further child groups or channels, forming a nested hierarchy. Notably, c
...within the Magistrala.

2024-03-20 15:37 UTC, dborovcanin commented on docs/authorization.md
> +A group serves as a parent entity that can contain both groups and channels as children. Child groups, in turn, can consist of further child groups or channels, forming a nested hierarchy. Notably, c
Always capitalize `Magistrala` in other places, as well.

2024-03-20 15:37 UTC, dborovcanin commented on docs/authorization.md
> +Actions related to the creation, updation, and deletion of things, channels, and groups are not permitted, requests will fail in authorization. In magistrala operations related to things, channels, a
...creation, update, and deletion...

2024-03-21 08:08 UTC, dborovcanin commented on docs/authorization.md
> +Actions related to the creation, updation, and deletion of things, channels, and groups are not permitted, requests will fail in authorization. In magistrala operations related to things, channels, a
@arvindh123 Please address this one, as well.

2024-03-21 08:14 UTC, dborovcanin requested changes

2024-03-21 08:14 UTC, dborovcanin commented on docs/authorization.md
> +Actions related to the creation, updation, and deletion of things, channels, and groups are not permitted, requests will fail in authorization. In magistrala operations related to things, channels, a
Also, use capital and change: _~In~ Magistrala operations related to things..._

2024-03-21 08:23 UTC, dborovcanin approved these changes

2024-03-21 08:23 UTC, merged