NOISSUE  - v0.14.0 blog post
absmach/supermq-docs pull request #177
Opened 2024-03-07 13:52 UTC by rodneyosodo

### What does this do?
Submit blog post for review

### Which issue(s) does this PR fix/relate to?
No issue

### List any changes that modify/break current functionality
Magistrala v0.14.0 release blog post

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
Not to be merged but to be reviewed for publishing to https://medium.com/abstract-machines-blog

2024-03-07 14:12 UTC, arvindh123 reviewed
LGTM

2024-03-10 11:12 UTC, Musilah commented on docs/release.md
> +Magistrala now supports multi-tenancy with the introduction of domains! This exciting new feature allows for the separation of data and resources between different users or organizations. While we're
Could you capitalise the first letter in magistrala.

2024-03-10 11:13 UTC, Musilah commented on docs/release.md
> +Remember web sockets? We're thrilled to announce its return to Magistrala, built from scratch for improved performance and exciting possibilities. This isn't just a revival – we're actively planning
This is the third 'we're thrilled to announce'. Perhaps a different clause.

2024-03-10 11:14 UTC, Musilah commented on docs/release.md
> +Invitation service is a new feature in magistrala. This service is responsible for sending invitations to users to join a domain. This is a very important feature for multi-tenancy. We currently don'
Capitalize M in Magistrala

2024-03-10 11:15 UTC, Musilah commented on docs/release.md
> +Magisterala takes a monumental leap forward in event handling with the introduction of multiple event store support. No longer limited to Redis, you now have the freedom to choose between NATS Jetstr
Wrong Magistrala spelling here

2024-03-13 08:57 UTC, Musilah commented on docs/release.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/psTSFMoa4f4?si=Gx-Fi0hpe3RBv3jK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encr
This image doesn't show up locally

2024-03-20 20:07 UTC, rodneyosodo commented on docs/release.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed/psTSFMoa4f4?si=Gx-Fi0hpe3RBv3jK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encr
I can see it from my side in incognito mode. Are you able to see this video?

2024-04-17 10:44 UTC, dborovcanin approved these changes, later dismissed

2024-04-18 08:06 UTC, dborovcanin requested changes

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/index.md
> +- [What's New in Magistrala v0.14.0](./v0-14-0-release.md)
Let's reorder.

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +- Added support for multiple event stores
multiple -> numerous

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +- Add graceful-stop for HTTP and gRPC servers
Add -> Added

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +- Add prometheus and grafana for metrics
added Prometheus and Grafana for metrics

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +- Improve event sourcing
Improved, upgraded, use past tense.

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +Invitation service is a new feature in Magistrala. This service is responsible for sending invitations to users to join a domain. This is a very important feature for multi-tenancy. We currently don'
This is an essential feature for multi-tenancy.

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +Remember web sockets? We are ecstatic to reveal its return to Magistrala, built from scratch for improved performance and exciting possibilities. This isn't just a revival – we're actively planning f
Remember the WebSocket adapter? We are happy to reveal its return...

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +Invitation service is a new feature in Magistrala. This service is responsible for sending invitations to users to join a domain. This is a very important feature for multi-tenancy. We currently don'
Capitalize `Invitations` service, `Users` service.

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +### Add graceful-stop for HTTP and GRPC servers
Same, use the past tense; Added.

2024-04-18 08:06 UTC, dborovcanin commented on docs/blogs/v0-14-0-release.md
> +### Added support for multiple MQTT message brokers
Maybe something like: Expanded compatibility across various MQTT brokers?

2024-04-19 13:15 UTC, dborovcanin approved these changes

2024-04-19 13:15 UTC, merged