NOISSUE- Update cli usage
absmach/supermq-docs pull request #178
Opened 2024-03-13 10:56 UTC by JeffMboya

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Update magistrala cli usage

### Which issue(s) does this PR fix/relate to?

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2024-03-13 11:06 UTC, rodneyosodo requested changes

2024-03-13 11:06 UTC, rodneyosodo commented on docs/cli.md
> +Magistrala has two services: users and things.
Magistrala doesn't have 2 services. Either reword it or remove it

2024-03-13 11:06 UTC, rodneyosodo commented on docs/cli.md
> +  cli [command]
```suggestion
  magistrala-cli [command]
```

Same as all other places

2024-03-13 12:03 UTC, JeffMboya commented on docs/cli.md
> +  cli [command]
okay

2024-03-13 12:10 UTC, rodneyosodo requested changes

2024-03-13 12:10 UTC, rodneyosodo commented on docs/cli.md
> +  -h, --help                   help for magistrala-cli
Update the output from `magistrala-cli`

2024-03-13 20:28 UTC, rodneyosodo requested changes
Also, rename all occurrences of mainflux to magistrala appropriately

2024-03-13 20:28 UTC, rodneyosodo commented on config.toml
> +user_token = ""
We don't need this file

2024-03-14 15:26 UTC, drasko requested changes
Be careful with this renaming - new project name is Magistrala. Only Gitter currently stayed at Mainflux, and we need to change that as well.

2024-03-14 15:26 UTC, drasko commented on CONTRIBUTING.md
> +hosted on the [Magistrala Organization](https://github.com/mainflux) on GitHub.
Nope ;)

2024-03-14 15:26 UTC, drasko commented on CONTRIBUTING.md
> +git remote add upstream https://github.com/mainflux/docs.git
Nope

2024-03-14 16:55 UTC, JeffMboya commented on CONTRIBUTING.md
> +git remote add upstream https://github.com/mainflux/docs.git
Let me double check all the URLs

2024-03-15 14:11 UTC, rodneyosodo requested changes

2024-03-15 14:11 UTC, rodneyosodo commented on .github/CODEOWNERS
> +*   @magistrala/maintainers
This is not correct have a look at https://github.com/absmach/magistrala

2024-03-15 14:11 UTC, rodneyosodo commented on .gitignore
> +debug.log
Remove

2024-03-15 14:11 UTC, rodneyosodo commented on docs/api.md
> +To start working with the magistrala system, you need to create a user account.
Capitalize every instance of magistrala except for some rare cases where it is suffixed with something for example `magistrala-vault`

2024-03-15 14:11 UTC, rodneyosodo commented on docs/certs.md
> +[api-docs]: https://github.com/absmach/magistrala/blob/7a2f71a6c1e612e26839eef99f4c99d7f76d9dad/api/openapi/certs.yml#L4
This should be from main also remove line number notation

2024-03-15 14:11 UTC, rodneyosodo commented on docs/edge.md
> +magistrala_HOST='magistrala.com'
```suggestion
MAGISTRALA_HOST='magistrala.com'
```

Same as the surrounding occurrences

2024-03-18 08:27 UTC, rodneyosodo requested changes

2024-03-18 08:27 UTC, rodneyosodo commented on .github/CODEOWNERS
> +*   @magistrala/MAINTAINERS
Add a new line

2024-03-18 08:27 UTC, rodneyosodo commented on CONTRIBUTING.md
> +list](https://github.com/absmach/magistrala-docs) to determine if it already contains the
```suggestion
list](https://github.com/absmach/magistrala-docs/issues) to determine if it already contains the
```

2024-03-18 08:27 UTC, rodneyosodo commented on docs/certs.md
> +[magistrala-vault]: https://github.com/absmach/magistrala/blob/master/docker/addons/vault/README.md#setup
```suggestion
[magistrala-vault]: https://github.com/absmach/magistrala/blob/main/docker/addons/vault/README.md#setup
```

2024-03-19 07:56 UTC, rodneyosodo requested changes

2024-03-19 07:56 UTC, rodneyosodo commented on docs/cli.md
> +magistrala-cli health [service]
```suggestion
magistrala-cli health <service>
```

2024-03-19 08:20 UTC, rodneyosodo submitted a review, later dismissed
LGTM

2024-03-19 09:19 UTC, rodneyosodo submitted a review, later dismissed

2024-03-20 09:19 UTC, SammyOina submitted a review, later dismissed

2024-03-20 09:45 UTC, dborovcanin requested changes

2024-03-20 09:45 UTC, dborovcanin commented on docs/provision.md
> +magistrala-cli -m https://mainflux.com users create john.doe@email.com 12345678
There is no need for `-m` flag here.

2024-03-20 09:45 UTC, dborovcanin commented on docs/provision.md
> +magistrala-cli -m https://mainflux.com users token john.doe@email.com 12345678
Same here, remove `-m` and its value.

2024-03-20 12:32 UTC, dborovcanin approved these changes

2024-03-20 12:32 UTC, merged