NOISSUE - Updated bootstrap docs with detailed secure bootstrap config procedure
absmach/supermq-docs pull request #181
Opened 2024-03-25 11:54 UTC by nyagamunene

### What does this do?
This commit guides the user on how to get secure bootstrap configuration. It shows how to encrypt the thing's 
`external id` and then decry-pt the response.

### Which issue(s) does this PR fix/relate to?
There was no open issue related to this.

### List any changes that modify/break current functionality
This commit does not modify or break any current functionality. It guides the user on how to get secure bootstrap configuration.

### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
### Notes

2024-03-27 04:31 UTC, JeffMboya requested changes

2024-03-27 04:31 UTC, JeffMboya commented on docs/bootstrap.md
> +Here is a guide on how to get secure bootstrap configuration.
Remove this

2024-03-27 04:31 UTC, JeffMboya commented on docs/bootstrap.md
> +Once you have the encrypted external key, you can make a request to the Bootstrap service. Here's how you can do this using `curl`:
Once you have the encrypted external key, make....

2024-03-27 04:31 UTC, JeffMboya commented on docs/bootstrap.md
> +>Note: If you are making the request via the Magistrala CLI, this process is not required.
Remove this

2024-03-27 05:48 UTC, nyagamunene commented on docs/bootstrap.md
> +>Note: If you are making the request via the Magistrala CLI, this process is not required.
Let me remove the note

2024-03-27 08:50 UTC, JeffMboya submitted a review, later dismissed

2024-03-27 10:01 UTC, arvindh123 submitted a review, later dismissed

2024-03-27 10:33 UTC, dborovcanin requested changes

2024-03-27 10:33 UTC, dborovcanin commented on docs/bootstrap.md
> +```bash
Use `go` instead of `bash`.

2024-03-27 10:33 UTC, dborovcanin commented on docs/bootstrap.md
> +First, encrypt the external key of your thing using AES encryption. The encryption key is specified by the `MG_BOOTSTRAP_ENCRYPT_KEY` environment variable. Use a library or utility that supports AES
...using Go.

2024-03-27 10:33 UTC, dborovcanin commented on docs/bootstrap.md
> +Finally, decrypt the response using a function. Here's an example of how to do this using golang:
...using Go.

2024-03-27 10:33 UTC, dborovcanin commented on docs/bootstrap.md
> +```bash
Use `go`.

2024-03-27 13:08 UTC, dborovcanin requested changes

2024-03-27 13:08 UTC, dborovcanin commented on docs/bootstrap.md
> +First, encrypt the external key of your thing using AES encryption. The encryption key is specified by the `MG_BOOTSTRAP_ENCRYPT_KEY` environment variable. Use a library or utility that supports AES
Capitalize Go.

2024-03-27 13:08 UTC, dborovcanin commented on docs/bootstrap.md
> +Finally, decrypt the response using a function. Here's an example of how to do this using go:
Same here.

2024-03-29 14:19 UTC, dborovcanin requested changes

2024-03-29 14:19 UTC, dborovcanin commented on docs/bootstrap.md
> +
Remove the empty line.

2024-03-29 14:19 UTC, dborovcanin commented on docs/bootstrap.md
> +To use Magistrala CLI for the secure bootstrap configuration, use  the following command:
Remove duplicate whitespace in `use the following command`.

2024-03-29 14:30 UTC, dborovcanin approved these changes

2024-03-29 14:30 UTC, merged