NOISSUE - Update magistrala messaging
absmach/supermq-docs pull request #188
Opened 2024-05-20 23:23 UTC by nyagamunene

### What does this do?
It updated Magistrala messaging docs. It provides examples of how to do it.

### List any changes that modify/break current functionality
It adds the functionality of running Magistrala with TLS and MTLS.

### Have you included tests for your changes?
Yes.
### Did you document any new/modified functionality?
Yes
### Notes

2024-05-22 11:39 UTC, 1998-felix requested changes

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +> While using MTLS the `thing.crt` and `thing.crt` can be genarated by running `make thing_cert` while in the `docker/ssl` folder
thing.key and thing crt.

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +> While using MTLS the `thing.crt` and `thing.crt` can be genarated by running `make thing_cert` while in the `docker/ssl` folder
Also as it is mtls would it be more appropriate to have magistrala-client.key and magistrala-client.crt

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +The following environmental variables are used to enable or disable HTTP with TLS and MTLS: `MG_HTTP_ADAPTER_CERT_FILE`,`MG_HTTP_ADAPTER_KEY_FILE`, `MG_HTTP_ADAPTER_SERVER_CA_FILE`, `MG_HTTP_ADAPTER_
```suggestion
The following environment variables are used to enable or disable HTTP with TLS and MTLS: `MG_HTTP_ADAPTER_CERT_FILE`,`MG_HTTP_ADAPTER_KEY_FILE`, `MG_HTTP_ADAPTER_SERVER_CA_FILE`, `MG_HTTP_ADAPTER_CLIENT_CA_FILE`. These can be located in the `docker/.env` file.
```

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +To use magistala HTTP without TLS, comment out all of the listed environment variables provided above. To publish message over channel, thing should send following request:
You can also mention or provide an example for subscribing.

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +The following environmental variables are used to enable or disable MQTT with TLS and MTLS: `MG_MQTT_ADAPTER_CERT_FILE`, `MG_MQTT_ADAPTER_KEY_FILE`, `MG_MQTT_ADAPTER_SERVER_CA_FILE`, `MG_MQTT_ADAPTER
```suggestion
The following environment variables are used to enable or disable MQTT with TLS and MTLS: `MG_MQTT_ADAPTER_CERT_FILE`, `MG_MQTT_ADAPTER_KEY_FILE`, `MG_MQTT_ADAPTER_SERVER_CA_FILE`, `MG_MQTT_ADAPTER_CLIENT_CA_FILE`.
```

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +To use magistala mqtt without TLS, comment all of the listed environment variables provided above. To publish message over channel, thing should call following command:
```suggestion
To use magistala mqtt without TLS, comment all of the listed environment variables provided above. To publish message over channel, thing should send following request:
```

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +Uncomment out all of the above mentioned environment variables to enable MTLS certificates. Here is an example of how you would publish:
For consistency you could use the format you used above; `To subscribe to channel, thing should call following command:`

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +Here is how you would subscribe:
Same as above.

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +mosquitto_pub --id-prefix magistrala -u <thing_id> -P <thing_secret> -t channels/<channel_id>/messages -h localhost -p 1883 -m '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n
For consistency with other flags you can consider using the shorthand -I

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +The following environmental variables are used to enable or disable MQTT-over-WS with TLS and MTLS: `MG_MQTT_ADAPTER_WS_CERT_FILE`,`MG_MQTT_ADAPTER_WS_KEY_FILE`, `MG_MQTT_ADAPTER_WS_SERVER_CA_FILE`,
```suggestion
The following environment variables are used to enable or disable MQTT-over-WS with TLS and MTLS: `MG_MQTT_ADAPTER_WS_CERT_FILE`,`MG_MQTT_ADAPTER_WS_KEY_FILE`, `MG_MQTT_ADAPTER_WS_SERVER_CA_FILE`, `MG_MQTT_ADAPTER_WS_CLIENT_CA_FILE`.
```

2024-05-22 11:39 UTC, 1998-felix commented on docs/messaging.md
> +// Load return a TLS configuration that can be used in TLS servers
```suggestion
// LoadTLS returns a TLS configuration that can be used in TLS servers
```

2024-05-22 12:10 UTC, JeffMboya commented on docs/messaging.md
To send and receive messages over MQTT, you can use[Mosquitto tools][mosquitto]. If you prefer to use MQTT over WebSocket, you can use [Paho][paho].

2024-05-22 12:17 UTC, rodneyosodo requested changes
Also update coap messaging

2024-05-22 12:17 UTC, rodneyosodo commented on docs/messaging.md
> +
Add expected output

2024-05-22 12:17 UTC, rodneyosodo commented on docs/messaging.md
> +
same

2024-05-22 12:17 UTC, rodneyosodo commented on docs/messaging.md
> +curl -s -S -i -X POST -H "Content-Type: application/senml+json" -H "Authorization: Thing <thing_secret>" http://localhost/http/channels/<channel_id>/messages -d '[{"bn":"some-base-name:","bt":1.27602
For all examples add expected outputs

2024-05-22 12:22 UTC, 1998-felix requested changes

2024-05-22 12:22 UTC, 1998-felix commented on docs/messaging.md
> +Uncomment out all of the above mentioned environment variables to enable MTLS certificates.
```suggestion
Uncomment all of the above mentioned environment variables to enable MTLS certificates.
```

2024-05-22 12:22 UTC, 1998-felix commented on docs/messaging.md
> +// Load return a TLS configuration that can be used in TLS servers
```suggestion
// LoadTLS returns a TLS configuration that can be used in TLS servers
```

2024-05-22 12:22 UTC, 1998-felix commented on docs/messaging.md
> +Uncomment out the following environment variables: `MG_MQTT_ADAPTER_WS_CERT_FILE`,`MG_MQTT_ADAPTER_WS_KEY_FILE` and comment out the rest to enable TLS certificates.
```suggestion
Uncomment  the following environment variables: `MG_MQTT_ADAPTER_WS_CERT_FILE`,`MG_MQTT_ADAPTER_WS_KEY_FILE` and comment out the rest to enable TLS certificates.
```

2024-05-22 12:22 UTC, 1998-felix commented on docs/messaging.md
> +Here is an example of how you would publish:
Could you try: 
Here is an example of a go program connecting to Magistrala server and sending  messages over MQTT without TLS using paho mqtt library:

2024-05-22 12:27 UTC, JeffMboya requested changes

2024-05-22 12:27 UTC, JeffMboya commented on docs/messaging.md
To send and receive messages over MQTT, you can use [Mosquitto tools][mosquitto]. If you prefer to use MQTT over WebSocket, you can use [Paho][paho].

2024-05-22 12:27 UTC, JeffMboya commented on docs/messaging.md
To subscribe to channel, thing should send following request:

2024-05-22 12:27 UTC, JeffMboya commented on docs/messaging.md
> +Uncomment out all of the above mentioned environment variables to enable MTLS certificates. Here is an example of how you would publish:
I think it would be better to use: `To subscribe to channel, thing should send following request:`

2024-05-22 12:49 UTC, JeffMboya requested changes

2024-05-22 12:49 UTC, JeffMboya commented on docs/messaging.md
> +To subscribe to channel, thing should call following command:
```suggestion
To subscribe to channel, thing should send following request:
```

2024-05-22 12:49 UTC, JeffMboya commented on docs/messaging.md
>  To send and receive messages over MQTT you could use [Mosquitto tools][mosquitto], or [Paho][paho] if you want to use MQTT over WebSocket.
```suggestion
To send and receive messages over MQTT, you can use [Mosquitto tools][mosquitto]. If you prefer to use MQTT over WebSocket, you can use [Paho][paho].
```

2024-05-22 12:49 UTC, JeffMboya commented on docs/messaging.md
> +Uncomment out all of the above mentioned environment variables to enable MTLS certificates. Here is an example of how you would publish:
I think it would be better to use: `To subscribe to channel, thing should send following request:` like you suggested in one of the comments above

2024-06-26 13:19 UTC, dborovcanin commented
@nyagamunene @JeffMboya What's the status of this PR?

2024-06-26 13:25 UTC, nyagamunene commented
> @nyagamunene @JeffMboya What's the status of this PR?

It was placed on hold because it is dependant on this [PR](https://github.com/absmach/magistrala/pull/2206)

2024-12-18 10:53 UTC, dborovcanin commented
@nyagamunene What's the status of this PR?

2024-12-18 11:25 UTC, nyagamunene commented
> @nyagamunene What's the status of this PR?

This is ready

2025-06-19 10:50 UTC, arvindh123 commented
This PR is related to https://github.com/absmach/supermq/issues/2126

2026-01-19 16:01 UTC, arvindh123 commented
This is address in different PR

2026-01-19 16:01 UTC, closed without merging