NOISSUE - Remove Prefixed `signin` and `signup` state
absmach/supermq-docs pull request #189
Opened 2024-06-04 10:40 UTC by rodneyosodo

### What does this do?
Removes `signin` and `signup` states which are prefixed to distinguish between signin and signup process

### Which issue(s) does this PR fix/relate to?
Related to https://github.com/absmach/magistrala/pull/2270

Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
Not needed

### Did you document any new/modified functionality?
Yes

### Notes

2024-06-05 06:06 UTC, arvindh123 requested changes

2024-06-05 06:06 UTC, arvindh123 commented on docs/authentication.md
> +Magistrala handles the authentication callback at `<MG_BASE_URL>/google-callback` endpoint, where `<MG_BASE_URL>` is the base URL of your Magistrala instance. This endpoint needs to be registered in
So we will get error if user already exits in Magistrala ?  
```
so if the user already exists, the error will be sent to the UI via the error cookie. Finally, the user is redirected to the URL provided in `MG_USERS_UI_REDIRECT_URL` environment variable upon successful authentication.
```

2024-06-05 08:32 UTC, rodneyosodo commented on docs/authentication.md
> +Magistrala handles the authentication callback at `<MG_BASE_URL>/google-callback` endpoint, where `<MG_BASE_URL>` is the base URL of your Magistrala instance. This endpoint needs to be registered in
No, we don't get an error. Instead we register them and sign them in.

2024-08-12 08:51 UTC, dborovcanin approved these changes

2024-08-12 08:51 UTC, merged