Mg 193
absmach/supermq-docs pull request #194
Opened 2024-08-13 12:18 UTC by JeffMboya

Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
This PR updates Kubernetes.md to conform to the latest helm charts

### Which issue(s) does this PR fix/relate to

-Resolves #193 

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes

2024-08-15 06:41 UTC, arvindh123 requested changes
Please update

2024-08-15 06:41 UTC, arvindh123 commented on docs/kubernetes.md
>  | twins.httpPort                     | Twins service HTTP port                                                                         | 9021             |
@JeffMboya  Values.yaml  are changed a lot, please update here and if needed update the devops repo too

2024-08-16 08:58 UTC, arvindh123 requested changes

2024-08-16 08:58 UTC, arvindh123 commented on docs/kubernetes.md
> +| defaults.image.repository          | Docker Image Repository                                                                         | magistrala           |
I think this is removed , instead we have tag i guess, Please verify vaules.yaml in devops

2024-08-16 10:19 UTC, JeffMboya commented on docs/kubernetes.md
> +| defaults.image.repository          | Docker Image Repository                                                                         | magistrala           |
> I think this is removed , instead we have tag i guess, Please verify vaules.yaml in devops

![image](https://github.com/user-attachments/assets/27b2fee6-7c05-42cf-9727-70a9d3b72e22)

2024-08-21 07:30 UTC, felixgateru requested changes

2024-08-21 07:30 UTC, felixgateru commented on docs/kubernetes.md
> +You can easily customize Magistrala during installtion by overriding the default settings using the `--set` option in Helm.
```suggestion
You can easily customize Magistrala during installation by overriding the default settings using the `--set` option in Helm.
```

2024-08-21 07:30 UTC, felixgateru commented on docs/kubernetes.md
> +You need to expose the MQTT ports (`1883` for unencrypted and `8883` for encrypted messages) and the CoAP port (`5683` for UDP) in the NGINX Ingress Controller service. You can do that with the follw
```suggestion
You need to expose the MQTT ports (`1883` for unencrypted and `8883` for encrypted messages) and the CoAP port (`5683` for UDP) in the NGINX Ingress Controller service. You can do that with the following command that edits your service:
```

2024-08-22 06:59 UTC, felixgateru approved these changes, later dismissed

2024-08-22 11:21 UTC, arvindh123 requested changes

2024-08-22 11:21 UTC, arvindh123 commented on docs/kubernetes.md
> +| mqtt.redisCachePort                | MQTT adapter Redis Auth Cache port                                                              | 6379                 |
@JeffMboya  Some of the values will not available in values.yaml, but template have values with defaults.

2024-09-07 20:11 UTC, dborovcanin commented
@JeffMboya Is this up to date and ready?

2024-09-08 14:13 UTC, JeffMboya commented
> @JeffMboya Is this up to date and ready?

@dborovcanin yes, this is up to date and ready

2024-09-09 08:22 UTC, dborovcanin approved these changes

2024-09-09 08:22 UTC, merged