MG-2041 - Add user's guide blogpost
absmach/supermq-docs pull request #195
Opened 2024-08-28 11:13 UTC by nyagamunene

### What does this do?

It adds a user guide blog post on how to use magistrala with examples

### Which issue(s) does this PR fix/relate to?
Resolves: #[MG-2041](https://github.com/absmach/magistrala/issues/2041)

### List any changes that modify/break current functionality
N/A
### Have you included tests for your changes?
N/A
### Did you document any new/modified functionality?
Yes
### Notes

2024-08-28 11:21 UTC, rodneyosodo requested changes

2024-08-28 11:21 UTC, rodneyosodo commented on config.toml
> +raw_output = "false"
This is not needed

2024-08-28 11:21 UTC, rodneyosodo commented on docs/blogs/user-guide.md
> +**Please note:** Magistrala offers a variety of services, each detailed comprehensively in the [architecture documentation](../architecture.md).
Since this will be published to medium use absolute links https://docs.magistrala.abstractmachines.fr/architecture/

2024-08-28 11:21 UTC, rodneyosodo commented on docs/blogs/user-guide.md
> +
Add step to login to domain

2024-08-28 11:21 UTC, rodneyosodo commented on docs/blogs/user-guide.md
> +magistrala-cli messages send $CHANNELID '[{"bn":"Dev1","n":"temp","v":20}, {"n":"hum","v":40}]' <thing_secret>
Add instruction on how to get thing secret

2024-08-28 11:21 UTC, rodneyosodo commented on docs/blogs/user-guide.md
> +```bash
This should start before using `magistrala-cli`

2024-09-04 06:53 UTC, rodneyosodo requested changes

2024-09-04 06:53 UTC, rodneyosodo commented on docs/blogs/user-guide.md
> +[Twitter-handle]: https://x.com/absmach?t=9j4nWw8EKQJ_-IPSPbDY8g&s=09
```suggestion
[Twitter-handle]: https://x.com/absmach
```

2024-09-04 06:53 UTC, rodneyosodo commented on docs/blogs/user-guide.md
> +magistrala-cli messages send $CHANNELID '[{"bn":"Dev1","n":"temp","v":20}, {"n":"hum","v":40}]' <thing_secret>
From the naming of the thing and channel, it is assumed it will be sending distance in cm correct this.

Something like

```json
{
  "name": "Pressure Sensor Tank A",
  "metadata": {
    "type": "sensor",
    "location": "Tank A",
    "manufacturer": "Acme Corp",
    "model": "PS-2000",
    "installation_date": "2023-05-12",
    "maintenance_due": "2024-05-12",
    "communication_protocol": "MQTT",
    "battery_level": 90
  },
  "tags": [
    "pressure",
    "tank",
    "critical"
  ]
}
```

```json
{
  "name": "Tank A Outlet Pressure",
  "metadata": {
    "unit": "bar",
    "sampling_interval": "10s",
    "data_type": "float",
    "min_value": 0,
    "max_value": 10,
    "precision": 0.01,
    "threshold_warning": 8.5,
    "threshold_critical": 9.5
  }
}
```

```json
[
  {
    "bn": "<device-serial-number>",
    "n": "Pressure_TankA_Outlet",
    "u": "bar",
    "v": 7.8
  },
  {
    "n": "BatteryLevel",
    "u": "%",
    "v": 88
  }
]
```

2024-09-04 13:31 UTC, rodneyosodo requested changes

2024-09-04 13:31 UTC, rodneyosodo commented on config.toml
> +raw_output = "false"
Remove

2024-09-04 14:16 UTC, JeffMboya requested changes

2024-09-04 14:16 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +In the rapidly evolving landscape of Industrial Internet of Things (IIoT), businesses are constantly seeking robust, scalable, and secure solutions to manage their connected devices and data. Enter M
```suggestion
In the world of Industrial Internet of Things (IIoT), businesses are always on the lookout for reliable, scalable, and secure ways to handle their connected devices and data. That's where Magistrala comes in—an open-source IIoT platform that's transforming the way we approach industrial automation and remote monitoring.
```

2024-09-04 14:16 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +- Clone the Magistrala repository:
```suggestion
- Clone the Magistrala repository and navigate to the newly created directory:
```

2024-09-04 14:16 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +To initiate the Magistrala Docker services, execute the following command from the project's root directory:
```suggestion
To start Magistrala Docker services, execute the following command from the project's root directory:
```

2024-09-04 14:16 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +- Start the Magistrala Docker services:
```suggestion
```

2024-09-04 14:16 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +The platform offers multiple interaction options, including a CLI, SDK, HTTP API, and UI, catering to different user preferences and use cases.
```suggestion
Magistrala offers multiple interaction options, including a CLI, SDK, HTTP API, and UI, catering to different user preferences and use cases.
```

2024-09-04 14:16 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +**Note:** The access token will need to set to the environmental variable created earlier. While logged into your domain there are muliple things that can be done. Let go through some of them.
```suggestion
**Note:** The access token will need to be set to the `ACCESSTOKEN` environmental variable created earlier. While logged into your domain, there are multiple operations that can be done. Let go through some of them.
```

2024-09-04 17:40 UTC, rodneyosodo approved these changes, later dismissed

2024-09-05 07:25 UTC, JeffMboya approved these changes

2024-09-06 10:26 UTC, JeffMboya requested changes

2024-09-06 10:26 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +- Clone the Magistrala repository and navigate to the newly created directory:
```suggestion
- From the terminal, clone the Magistrala repository and navigate to the newly created directory:
```

2024-09-06 10:26 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +Setting up Magistrala is straightforward. With Docker (version 26.0.0 and above) and Go (version 1.21 and above) installed on your system, you can clone the official GitHub repository and have the pl
```suggestion
Setting up Magistrala is straightforward. First, the following are needed:
- [Docker](https://docs.docker.com/install/) (version 26.0.0 and above)
- [Go](https://golang.org/doc/install) (version 1.21 and above)

With Docker (version 26.0.0 and above) and Go (version 1.21 and above) installed on your system, you clone the official Magistrala GitHub repository and have the platform up and running in no time. Here's a quick guide to get you started:
```

2024-09-06 10:26 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +Magistrala's Command Line Interface (CLI) provides a powerful way to interact with the platform. There are many commands available through the CLI. For more information, run:
```suggestion
Magistrala's Command Line Interface (CLI) provides a powerful way to interact with the platform. There are many commands available through the CLI. For more information, refer to the [Magistrala CLI Documentation](https://docs.magistrala.abstractmachines.fr/cli/). To explore available commands and get usage details, run:
```

2024-09-06 10:26 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +- Generate an access token:
```suggestion
- After creating a user, you need to generate an access token for them. To do so, run:
```

2024-09-06 10:26 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +   The access token can be set to an environmental variable to allow for easy use:
```suggestion
   This generates an access token and a refresh token for the created user. The access token is used for authentication in subsequent operations, while the refresh token allows you to generate a new access token when the existing access token expires. For convenience, both tokens can be set as environment variables for easy access:
```

2024-09-06 10:26 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +ACCESSTOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgxOTI2MTIsImlhdCI6MTcxODE4OTAxMiwiaXNzIjoibWFnaXN0cmFsYS5hdXRoIiwidHlwZSI6MCwidXNlciI6ImMxYjQ3OWQwLWEzNDYtNGZiYy1hN2FkLWVkNGFiNjcxYTIyZC
```suggestion
```bash
ACCESSTOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgxOTI2MTIsImlhdCI6MTcxODE4OTAxMiwiaXNzIjoibWFnaXN0cmFsYS5hdXRoIiwidHlwZSI6MCwidXNlciI6ImMxYjQ3OWQwLWEzNDYtNGZiYy1hN2FkLWVkNGFiNjcxYTIyZCJ9._Qlri9FN_E2vJLZIVQzyeeg9I_ggVRi_CKS52xlUD8YEkSKWkTlmr02WlKdhvR-aZzaDyudICLtCPtadMCGCzg

REFRESHTOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU3MDM4NTUsImlhdCI6MTcyNTYxNzQ1NSwiaXNzIjoibWFnaXN0cmFsYS5hdXRoIiwidHlwZSI6MSwidXNlciI6IjM0YzNhMDhjLTBkMzEtNGU3Ny1iNjBlLTA0OTBiOTc5NzQyMSJ9.v9tFiX2NKiykg1SmmwNQrSDlcsNrYp7isF0kqTzyo8wiJuYfvO7GwCKNb1aGPx6uR6_VYGQlfN6aoxAKP_42WQ
```

2024-09-06 10:26 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +**Note:** The token last for 15 minutes before expiring and will need the user to get a new one.
```suggestion
**Note:** The access token is valid for 15 minutes before it expires. After this period, the user will need to use the refresh token to obtain a new access token.
```

2024-09-06 11:33 UTC, JeffMboya requested changes

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +
```suggestion
After creating a user and generating access and refresh tokens, you need to add the user to a domain to access resources within the platform. To assign the user to a domain, you need to create a domain (workspace) using the following command:
```

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +Save the domain Id to use it for logging in:
```suggestion
Save the domain ID in an environment variable `DOMAINID` for ease of use for logging in:
```

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +To login into your workspace to generate the token with the domain ID attached:
```suggestion
To login into the created domain/ workspace, you need to embed the token with the domain ID. Including the domain ID in the token ensures that the token is specific to the domain/workspace, which is essential for managing access and permissions within that particular domain/workspace. To do so, run:
```

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +magistrala-cli domain create workspace alias $ACCESSTOKEN
```suggestion
magistrala-cli domains create workspace alias $ACCESSTOKEN
```

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +**Note:** The access token will need to be set to the `ACCESSTOKEN` environmental variable created earlier. While logged into your domain, there are multiple operations that can be done. Let go throu
```suggestion
Update the `ACCESSTOKEN` and `REFRESHTOKEN` environment variables with the newly generated tokens (token with domain ID attached). 

While logged into your domain, you can perform a variety of operations. Some of the key operations include:

- User Management: Manage users within your domain, including creating, updating, and deleting user accounts.
- Things Management: Manage devices or "things" associated with your domain, including adding, updating, and monitoring their status.
- Channel Management: Configure and manage channels for data communication within the domain.
- Domain Management: Handle domain-specific settings and configurations.

For more detailed information on these operations, refer to the [Magistrala CLI Documentation](https://docs.magistrala.abstractmachines.fr/cli/). Let us go through some of the operations.
```

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +**Note:** The secret for the thing can be specified during its creation. If not provided, it will be automatically generated by the platform. To view the generated secret, please access the profile a
```suggestion
**Note:** The secret for the thing can be specified during its creation. If not provided, it will be automatically generated by the platform. To view the generated secret, please access the thing profile as follows:
```

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +magistrala-cli messages read $CHANNELID $ACCESSTOKEN
@nyagamunene 
```bash
magistrala-cli messages read $CHANNELID $ACCESSTOKEN             

error: Status: : Get "http://localhost:9011/channels/e54b2069-9468-49a2-bb48-4a317a13ab33/messages?limit=10&offset=0&total=0": dial tcp 127.0.0.1:9011: connect: connection refused
```

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +
```suggestion
**Note:** Make sure to replace `$THINGID`, `$THINGSECRET`, and `$ACCESSTOKEN` with your actual Thing ID, Thing secret, and access token values, respectively.
```

2024-09-06 11:33 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +magistrala-cli domains assign users member '[<user_id>]' $DOMAINID $ACCESSTOKEN
@nyagamunene please check this

2024-09-06 12:14 UTC, JeffMboya requested changes

2024-09-06 12:14 UTC, JeffMboya commented on docs/blogs/user-guide.md
> +For more information about using HTTP api, refer to the [documentation][swagger-docs] on swagger.
```suggestion

The `--curl` flag in `magistrala-cli`, provides the equivalent `curl` request that the CLI would execute. This can be helpful for debugging or using the command outside of the CLI. For example, when you create a new user with the following command:

```bash
magistrala-cli users create john johndoe@example.com 12345678 --curl
```
You will receive the equivalent `curl` command:

```bash
2024/09/06 15:00:30 curl -X 'POST' -d '{"id":"","name":"john","credentials":{"identity":"johndoe@example.com","secret":"12345678"},"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z","status":"enabled"}' -H 'Content-Type: application/json' 'http://localhost:9002/users'
```
The output shows the HTTP request that the CLI would execute, allowing you to copy and paste it for manual execution with `curl`. For more information about using HTTP api, refer to the [documentation][swagger-docs] on swagger.
```

2024-09-06 15:09 UTC, JeffMboya approved these changes

2024-09-07 20:07 UTC, dborovcanin approved these changes

2024-09-07 20:07 UTC, merged