MG-198 - Add post-deployment guide for K8s
absmach/supermq-docs pull request #199
Opened 2024-09-19 07:00 UTC by JeffMboya

### What does this do?
This PR adds a section to the README file explaining how to interact with Magistrala services after K8s deployment, both through the web-based User Interface (UI) and via Postman. 

### Which issue(s) does this PR fix/relate to?
- Resolve #198

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
This update is important for users deploying Magistrala on a Kubernetes cluster, particularly with a DigitalOcean load balancer, as it provides clear steps for accessing and interacting with the deployed services.

2024-09-23 09:20 UTC, dborovcanin requested changes

2024-09-23 09:20 UTC, dborovcanin commented on docs/kubernetes.md
> +- via Postman
Once you have successfully deployed Magistrala, there are three primary ways you can interact with its services:

- web-based User Interface (UI)
- Magistrala CLI tool
- HTTP API Clients (e.g., cURL, Postman)

2024-09-23 09:20 UTC, dborovcanin commented on docs/kubernetes.md
> +###### 1. Set Up the Postman Request
Upload a Postman collection (you can even generate it from the API docs) and add a link to it.

2024-09-24 08:35 UTC, arvindh123 requested changes

2024-09-24 08:35 UTC, arvindh123 commented on .github/CODEOWNERS
> +- @absmach/maintainers
Revert this back to original

2024-09-24 13:07 UTC, dborovcanin requested changes

2024-09-24 13:07 UTC, dborovcanin commented on docs/kubernetes.md
> +- Magistrala CLI tool
Add a link to the CLI docs at https://docs.magistrala.abstractmachines.fr/cli.

2024-09-24 19:33 UTC, dborovcanin approved these changes

2024-09-24 19:33 UTC, merged