NOISSUE - Add documentation related to subjects filtering in writer services
absmach/supermq-docs pull request #20
Opened 2020-03-28 14:04 UTC by jonathandreyer

Signed-off-by: Jonathan Dreyer <jonathan.dreyer@cleanenergie.ch>

2020-03-28 16:41 UTC, drasko requested changes

2020-03-28 16:41 UTC, drasko commented on docs/storage.md
> +Regarding the [Subtopics Section](messaging.md#subtopics) in the messaging page, the example `channels/<channel_id>/messages/bedroom/temperature` can be filtered as `"*.bedroom.temperature"`. The for
I am not sure that `channels/<channel_id>/messages/bedroom/temperature` can be filtered as `"*.bedroom.temperature"`. I think you would need `channels.*.messages.bedroom.temperature`. Please check this.

2020-03-28 16:49 UTC, manuio commented on docs/storage.md
> +Regarding the [Subtopics Section](messaging.md#subtopics) in the messaging page, the example `channels/<channel_id>/messages/bedroom/temperature` can be filtered as `"*.bedroom.temperature"`. The for
@drasko His last version add the prefix `channel.` to subjects but we could move this prefix in the config file.

2020-03-28 17:06 UTC, jonathandreyer commented on docs/storage.md
> +Regarding the [Subtopics Section](messaging.md#subtopics) in the messaging page, the example `channels/<channel_id>/messages/bedroom/temperature` can be filtered as `"*.bedroom.temperature"`. The for
@drasko To be more precise, the prefix is set in the file `topics.go` as the constant `InputChannels`.

2020-03-28 17:54 UTC, manuio commented on docs/storage.md
> +Regarding the [Subtopics Section](messaging.md#subtopics) in the messaging page, the example `channels/<channel_id>/messages/bedroom/temperature` can be filtered as `"*.bedroom.temperature"`. The for
@jonathandreyer btw, I would rename this `InputChannels`. Maybe `topicAllChannels`

2020-03-28 18:35 UTC, drasko requested changes

2020-03-28 18:35 UTC, drasko commented on docs/storage.md
> +Regarding the [Subtopics Section](messaging.md#subtopics) in the messaging page, the example `channels/<channel_id>/messages/bedroom/temperature` can be filtered as `"*.bedroom.temperature"`. The for
I see. Please remove this const, and the use the full subject that comes from config file. I prefer having explicit full path in `subjects` as not we allow subtopics as well, so it will be a mess if only parts of NATS subjects are defined here.

2020-03-28 21:05 UTC, jonathandreyer commented
@drasko OK, I see what you propose. I have an interrogation but I will ask in the other repository because it is more related to this repository.

2020-03-29 12:31 UTC, manuio approved these changes
LGTM

2020-03-31 11:19 UTC, drasko approved these changes
LGTM

2020-03-31 14:38 UTC, merged