NOISSUE - Rename Magistrala to SuperMQ in docs repo
absmach/supermq-docs pull request #205
Opened 2024-12-09 06:44 UTC by Musilah

Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
This PR renames the magistrala docs to superMQ
### Which issue(s) does this PR fix/relate to?

Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)
N/A
### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2024-12-10 10:20 UTC, wambui-pixel reviewed
Logo is too small
![image](https://github.com/user-attachments/assets/6acb456d-cf5d-44ce-ad59-15a324212617)

2024-12-10 10:32 UTC, wambui-pixel requested changes
the on-hover is a bit too dark
![image](https://github.com/user-attachments/assets/86b2d4dd-69b0-4207-80a1-e24d9d69955f)

2024-12-10 10:34 UTC, wambui-pixel requested changes
1. The logo is bigger in dark mode
2. The active color is not easily visible

![image](https://github.com/user-attachments/assets/758dec54-e1b0-4caf-bec3-50c07cbc8ae7)

2024-12-10 10:36 UTC, wambui-pixel requested changes
1. Increase the size, especially of the home logo
2. This font headers look a bit off.
3. We should switch this image to one that uses `superMQ`, and not `Mainflux`

![image](https://github.com/user-attachments/assets/849c6ce7-401b-4693-9d2e-299642b93c2f)

2024-12-10 17:13 UTC, ianmuchyri requested changes

2024-12-10 17:13 UTC, ianmuchyri commented on docusaurus.config.ts
> +          // feedOptions: {
remove commented out code if not needed

2024-12-10 17:13 UTC, ianmuchyri commented on docusaurus.config.ts
> +    // Replace with your project's social card - what is a social card?
do you need this comment?

2024-12-10 17:13 UTC, ianmuchyri commented on docusaurus.config.ts
> +      copyright: `Copyright © ${new Date().getFullYear()} Abstract Machines. Built with Docusaurus.`,
Are we explicitly required to mention this part?
```
Built with Docusaurus.
```

2024-12-10 17:13 UTC, ianmuchyri commented on package.json
> +  "version": "0.0.0",
Give it a proper `SemVer` like `0.1.0`

2024-12-10 17:13 UTC, ianmuchyri commented on static/CNAME
> +docs.supermq.abstractmachines.fr
add empty line

2024-12-10 17:13 UTC, ianmuchyri commented on static/.nojekyll
what is the purpose of this file? It is empty. If it's not being used for anything please remove it

2024-12-10 17:13 UTC, ianmuchyri commented on static/img/docusaurus-social-card.jpg
do we need this docusaurus image?

2024-12-10 20:38 UTC, Musilah commented on docusaurus.config.ts
> +    // Replace with your project's social card - what is a social card?
I left it in in case we needed a social card later on. I could not design one myself.

2024-12-10 20:50 UTC, Musilah commented on static/.nojekyll
This warning here makes it a required file: 
```
By default, GitHub Pages runs published files through [Jekyll](https://jekyllrb.com/). Since Jekyll will discard any files that begin with _, it is recommended that you disable Jekyll by adding an empty file named .nojekyll file to your static directory.
```
This is from: https://docusaurus.io/docs/deployment#docusaurusconfigjs-settings

2024-12-10 20:53 UTC, Musilah commented on static/CNAME
> +docs.supermq.abstractmachines.fr
This is a requirement by Github Pages. The `CNAME` file must contain just the domain name. Any extra spaces, blank lines, or additional content could prevent GitHub Pages from correctly associating the site with the custom domain.

2024-12-10 21:20 UTC, dborovcanin requested changes

2024-12-10 21:20 UTC, dborovcanin commented on docs/opcua.md
> +[opcua-adapter]: https://github.com/absmach/supermq/tree/main/opcua
OPC UA adapter has been moved to contrib repo, you can remove it from here.

2024-12-10 21:20 UTC, dborovcanin commented on docs/provision.md
> +[env]: https://github.com/absmach/supermq/blob/main/.env
This link is incorrect. Please check other links, as well.

2024-12-10 21:20 UTC, dborovcanin commented on docs/tracing.md
> +| MG_JAEGER_URL       | Jaeger access from within SuperMQ              | jaeger:6831 |
Fix formatting. Also, env prefix now is `SMQ`, not `AM`.

2024-12-10 21:20 UTC, dborovcanin commented on docs/lora.md
> +[lora-adapter]: https://github.com/absmach/supermq/tree/main/lora
LoRa is also moved to contrib. We should remove LoRa section (or rather move this to LoRa https://github.com/absmach/smq-contrib/tree/main/lora codebase), but we should mention contrib repo in docs as a good playground for adding new contributions.

2024-12-11 08:49 UTC, felixgateru requested changes
![image](https://github.com/user-attachments/assets/2a7304a9-ba6a-4cc6-846a-203890b1d5c9)

check whether you can have this rendered as go code similar to what is in mkdocs as well as other instances

2024-12-11 10:11 UTC, dborovcanin commented
![image](https://github.com/user-attachments/assets/df9dd894-8cf8-4a05-a21e-dde5f98d1ed9)
Rename `The Scalable, Secure IoT Cloud Platform` to `Event-driven Infrastructure for Modern Cloud` and `Scalable IoT Middleware` to `Scalable Messaging Middleware`.

2024-12-11 10:24 UTC, dborovcanin commented
![image](https://github.com/user-attachments/assets/184ec560-bb61-4f5c-9f01-7d8f23bdff04)
Group the sidebar in the following manner:

# Overview

# Architecture

# Concepts
- Entities
- Authentication
- Authorization
- Security
- Messaging

# Getting Started
- API
- CLI

# Developer's guide
- Events
- Tracing

# Storage

# Edge

# Certs

# Kubernetes

# SMQ-Contrib Repository
- LoRa
- OPC-UA
- Provision
- Twins Service
- Bootstrap

# Test Spec


Also, please update Storage links, since some of those addons are now in the contrib repo.

2024-12-11 12:11 UTC, dborovcanin requested changes
Please change section titles to avoid duplications:
![image](https://github.com/user-attachments/assets/462d1a87-2eee-4df2-bdf6-fd578d1b51c2)
Something like `Overview` will work, but try to think of something better, ideally different for each subsection.

2024-12-11 13:06 UTC, ianmuchyri approved these changes

2024-12-11 14:59 UTC, dborovcanin approved these changes

2024-12-11 15:01 UTC, merged