SMQ-209 - Fix Warnings for .svg Files During `yarn build`
absmach/supermq-docs pull request #214
Opened 2024-12-18 11:57 UTC by Musilah

### What does this do?

This fixes the warning that appears after a user runs `yarn build`. This warning has been cleared.
There is however a Babel warning that can be ignored since it does not really affect anything and the [Docusaurus](https://github.com/babel/babel/discussions/13676) team has advised to ignore as well.

### Which issue(s) does this PR fix/relate to?

Resolves #209 

### List any changes that modify/break current functionality

- [x] Fix svg files warnings
- [x] Add linter to workflows
- [x] Compact the .svg files that are affected by Babel

### Have you included tests for your changes?
No
### Did you document any new/modified functionality?
No
### Notes

2024-12-19 09:01 UTC, ianmuchyri submitted a review, later dismissed

2024-12-19 16:00 UTC, dborovcanin requested changes
![image](https://github.com/user-attachments/assets/9698326b-2c37-491a-b826-9fd4d2e83b74)
Rename `Device` to `Client`.

2024-12-19 21:29 UTC, dborovcanin requested changes
Also add Mermaid support https://docusaurus.io/docs/next/markdown-features/diagrams.

2024-12-20 09:36 UTC, dborovcanin submitted a review, later dismissed

2024-12-20 09:53 UTC, ianmuchyri requested changes

2024-12-20 09:53 UTC, ianmuchyri commented on src/pages/landing/index_backup.tsx
Since we no longer have a landing page, do we need this file? More so, do we need this landing folder?

2024-12-20 09:53 UTC, ianmuchyri commented on src/pages/landing/index_backup.tsx
Also remove `open_source.svg` and `scalability.svg` images that is used in this page if we are to delete this page

2024-12-20 12:57 UTC, ianmuchyri approved these changes

2024-12-20 13:00 UTC, merged