Add twins related documentation page
absmach/supermq-docs pull request #32
Opened 2020-05-04 12:14 UTC by darkodraskovic

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

2020-05-04 12:37 UTC, mteodor commented on docs/twins.md
> +```
add ```json

2020-05-04 13:44 UTC, drasko requested changes
Generally this looks well, but I would appreciate a diagram that shows where Digital Twin service sits in the system (connected to NATS to get the requests, sends notifications upon deltas, exposes API - so connected to NginX as well, and so on).

2020-05-04 13:44 UTC, drasko commented on docs/twins.md
> +- general data about twin itself, i.e. **twin's metadata**,
I would capitalize bullets, as you did below (for consistency)

2020-05-04 13:44 UTC, drasko commented on docs/twins.md
> +```
Add `bash` after triple backtick

2020-05-05 09:33 UTC, manuio requested changes

2020-05-05 09:33 UTC, manuio commented on docs/twins.md
>  ```
```json

2020-05-05 09:33 UTC, manuio commented on docs/twins.md
> +```
```json

2020-05-05 09:33 UTC, manuio commented on docs/twins.md
>  ```
```bash

2020-05-05 21:50 UTC, drasko commented
I think `WIP` label can be removed

2020-05-05 22:03 UTC, drasko commented
Also, please edit PR title and align it to Mainflux standard by prefixing it with `NOISSUE - `

2020-05-07 17:13 UTC, drasko submitted a review, later dismissed
LGTM

2020-05-07 17:24 UTC, dborovcanin requested changes

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +Digital twin is an abstract - and usually less detailed - digital replica of a
... - a digital replica of a real-world...

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +to compare system state over a given period of time - so called diffs or
... so-called...

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +possibly multiple [Mainflux things, channels and subtopics]((architecture.md)).
..., and subtopics...

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +cases and corresponds to the intended use of Mainlfux IoT platform, this setup
..., and corresponds...

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +beforehand. As you go, you can modify your things, channels and connections and
..., and connections...

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +two or more attributes with a same channel and subtopic in the same definition .
... the same channel and subtopic...

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +Attributes has a state persistance flag that determines whether the messages
Attributes have a state persistence...

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +communicated by it's corresponding channel and subtopic trigger the creation of
..its corresponding channel...

2020-05-07 17:24 UTC, dusanb94 commented on docs/twins.md
> +twins and states persistance is on the roadmap.
...persistence...

2020-05-07 17:31 UTC, dborovcanin requested changes

2020-05-07 17:31 UTC, dusanb94 commented on docs/twins.md
> +revisions is **2** (revision index is zero based). We decide not to persist the
...zero-based...

2020-05-07 17:31 UTC, dusanb94 commented on docs/twins.md
> +stores twin's ID - every state belongs to a single twin -, its own ID, twin's
typo `,` in  `...twin -, its...`

2020-05-07 17:31 UTC, dusanb94 commented on docs/twins.md
> +definition number, creation date and the actual payload. **Payload** is a set of
..., and the actual...

2020-05-07 17:31 UTC, dusanb94 commented on docs/twins.md
> +Twin belongs to a Mainflux user, tenant representing physical person or
...representing a physical person...

2020-05-07 17:31 UTC, dusanb94 commented on docs/twins.md
> +In practical terms, we need to create a Mainflux user in order to create digital
...in order to create a digital twin.

2020-05-07 17:31 UTC, dusanb94 commented on docs/twins.md
> +Create and update request use JSON body to initialize and modify, respectively,
Create and update requests... (plural)

2020-05-07 17:31 UTC, dusanb94 commented on docs/twins.md
> +The twins service will use the this channel to publish notifications related to
...will use ~the~ this channel...

2020-05-07 17:31 UTC, dusanb94 commented on docs/twins.md
> +by Mainflux - HTTP, MQTT, CoAP and WS - you can use any supported protocol
..., and WS...

2020-05-08 09:51 UTC, dborovcanin requested changes
In the architecture diagram, Things and Users services point to the same LocalDB. Even though it has nothing to do with Twins service, this can be misleading because these services use separate DBs. Can you use separate databases or remove `Local DB` from the diagram. If you decide to keep it, please align the color legend(red for storage) with it.

2020-05-08 09:54 UTC, darkodraskovic commented on docs/twins.md
> +Digital twin is an abstract - and usually less detailed - digital replica of a
There is an `a` in the whole phrase `an abstract - and usually less detailed - digital replica`.

2020-05-08 09:59 UTC, darkodraskovic commented on docs/twins.md
> +stores twin's ID - every state belongs to a single twin -, its own ID, twin's
You can put a comma after `-` if you target that.

2020-05-08 11:05 UTC, manuio commented on docs/twins.md
> +### Mainflux digital twin
You could add a new line before this tittle

2020-05-08 11:50 UTC, manuio commented on docs/twins.md
> +will be created.
Is this ok?

2020-05-08 12:12 UTC, dborovcanin approved these changes

2020-05-08 12:13 UTC, darkodraskovic commented on docs/twins.md
> +will be created.
Yes, cause I consistently make a newline after the code block. See here how it looks compiled https://github.com/darkodraskovic/docs/blob/twins/docs/twins.md#create

2020-05-08 12:38 UTC, drasko approved these changes
LGTM

2020-05-08 12:39 UTC, merged