MF-1125 - add provision service docs
absmach/supermq-docs pull request #33
Opened 2020-05-05 11:18 UTC by mteodor

https://github.com/mainflux/mainflux/issues/1125

2020-05-05 21:50 UTC, drasko commented
Please remove `WIP` label

2020-05-05 22:01 UTC, drasko requested changes

2020-05-05 22:01 UTC, drasko commented on docs/provision.md
> +Provision service provides an HTTP API to interact with [Mainflux][mainflux].
Tell us first what this service is, then what it provides.

2020-05-05 22:01 UTC, drasko commented on docs/provision.md
> +For gateways to communicate with [Mainflux][mainflux] configuration is required (mqtt host, thing, channels, certificates...). To get the configuration gateway will send a request to [Bootstrap][boot
It is unclear what is `configuration gateway`. Yuo mean `unconfigured gateway` maybe?

2020-05-05 22:01 UTC, drasko commented on docs/provision.md
> +To create bootstrap configuration you can use [Bootstrap][bootstrap] or `Provision` service. [Mainflux UI][mfxui] uses [Bootstrap][bootstrap] service for creating gateway configurations.  `Provision`
This is a bit confusing. Why UI uses Bootstrap when there is Provisioning? Maybe this is temporary slution, and UI will move to Provision?

2020-05-05 22:01 UTC, drasko commented on docs/provision.md
> +Provision service provides an HTTP API to interact with [Mainflux][mainflux].
Maybe als explain why we neded this service, the complexity of manual provisioning, what are the manual steps that can be automated, etc...

2020-05-05 22:01 UTC, drasko commented on docs/provision.md
> +By default, call to `/mapping` endpoint will create one thing and two channels (`control` and `data`) and connect it. If there is a requirement for different provision layout we can use [config](dock
Take care with these links, they will not work in `docs` repo, as they are relative

2020-05-06 14:28 UTC, mteodor commented on docs/provision.md
> +To create bootstrap configuration you can use [Bootstrap][bootstrap] or `Provision` service. [Mainflux UI][mfxui] uses [Bootstrap][bootstrap] service for creating gateway configurations.  `Provision`
that is something that we need to consider

2020-05-06 15:25 UTC, drasko commented on docs/provision.md
> +To create bootstrap configuration you can use [Bootstrap][bootstrap] or `Provision` service. [Mainflux UI][mfxui] uses [Bootstrap][bootstrap] service for creating gateway configurations.  `Provision`
OK, once you reach the conclusion, please write it here as a note.

2020-05-06 15:38 UTC, manuio requested changes

2020-05-06 15:38 UTC, manuio commented on docs/provision.md
> +For provisioning we can use [Mainflux CLI](./cli.md) creating users and for each node in the edge (eg. gateway) required number of things, channels, connecting them and creating certificates if neede
I would use `https://github.com/mainflux/mainflux/tree/master/cli` here

2020-05-06 15:39 UTC, manuio requested changes

2020-05-06 15:39 UTC, manuio commented on docs/provision.md
> +To create bootstrap configuration you can use [Bootstrap][bootstrap] or `Provision` service. [Mainflux UI][mfxui] uses [Bootstrap][bootstrap] service for creating gateway configurations.  `Provision`
Remove 1 white space before `  Provision service should provide`

2020-05-06 15:43 UTC, manuio requested changes

2020-05-06 15:43 UTC, manuio commented on docs/provision.md
> +Also you may use provision service to create certificates for each thing. Each service running on gateway may require more than one thing and channel for communication. Let's say that you are using s
I'm not convinced about `Let's say that` in docs.
Also, is this correct? `you will need two channels for Agent (data and control) and one for Export and one thing.`

2020-05-06 15:45 UTC, manuio requested changes

2020-05-06 15:45 UTC, manuio commented on docs/provision.md
> +Metadata can be whatever suits your needs except that at least one thing needs to have `external_id` (which is populated with value from [request](#example)). Thing that has `external_id` will be use
`Things Metadata must have an "external_id" field which is populated with... `

2020-05-07 09:43 UTC, manuio requested changes

2020-05-07 09:43 UTC, manuio commented on docs/provision.md
> +For provisioning we can use [Mainflux CLI][cli] for creating users
Is this return new line after `...creating users` ok?

2020-05-07 10:09 UTC, mteodor commented on docs/provision.md
> +For provisioning we can use [Mainflux CLI][cli] for creating users
this new line will not be rendered, if that is what you mean

2020-05-07 10:53 UTC, dborovcanin requested changes

2020-05-07 10:53 UTC, dusanb94 commented on docs/provision.md
> +Bootstrap configuration which can be fetched with [Agent][agent].
> Bootstrap configuration ~which~ can be fetched with [Agent][agent].

2020-05-07 10:53 UTC, dusanb94 commented on docs/provision.md
> +and sets-up different entities used in the platform - users, channels and things.
, and things.

2020-05-07 10:53 UTC, dusanb94 commented on docs/provision.md
> +It is part of process of setting up IoT application where
applications (plural)

2020-05-07 10:53 UTC, dusanb94 commented on docs/provision.md
> +and for each node in the edge (eg. gateway) required number of things, channels, connecting them and creating certificates if needed.
, and creating certificates

2020-05-07 10:53 UTC, dusanb94 commented on docs/provision.md
> +Provision service is used to setup initial applications configuration once user is created.
... is used to set up initial application...

2020-05-07 10:53 UTC, dusanb94 commented on docs/provision.md
> +in one http request instead of issuing several cli commands.
Please use capital letters in acronyms: HTTP request, MQTT protocol, CLI commands. Check for these in the rest of the document, as well.

2020-05-07 10:53 UTC, dusanb94 commented on docs/provision.md
> +For channels metadata `type` is reserved for `control` and `data` which we use with [Agent][agent].
For channels, metadata...

2020-05-07 10:53 UTC, dusanb94 commented on docs/provision.md
> +Additionally if you enabled mtls each service will need its own thing and certificate for access to [Mainflux][mainflux].
Additionally, if you enable mTLS...

2020-05-07 13:43 UTC, drasko requested changes

2020-05-07 13:43 UTC, drasko commented on docs/platform-management.md
> +used in the platform - users, channels and things.
No need to break line here

2020-05-07 13:43 UTC, drasko commented on docs/platform-management.md
> +Note that you will also need `user_auth_token` in order to create things
You can move this to the upper line

2020-05-07 13:43 UTC, drasko commented on docs/platform-management.md
> +an authorization key.
No need for line break here

2020-05-07 13:43 UTC, drasko commented on docs/platform-management.md
> +Multiple channels can be created by executing a `POST /things/bulk` request with a JSON payload.  The payload should contain a JSON array of the channels to be created.  If there is an error any of t
This line is actually good. Renders nicely, easy to read. Maybe align all to this style.

2020-05-07 16:25 UTC, drasko submitted a review, later dismissed
LGTM

2020-05-07 16:27 UTC, blokovi submitted a review, later dismissed

2020-05-07 17:12 UTC, dborovcanin requested changes

2020-05-07 17:12 UTC, dusanb94 commented on docs/platform-management.md
> +Provisioning is a process of configuration of an IoT platform in which system operator creates and sets-up different entities used in the platform - users, channels and things.
, and things.

2020-05-07 17:12 UTC, dusanb94 commented on docs/platform-management.md
> +You can specify `offset` and `limit` parameters in order to fetch specific group of things. In that case, your request should look like:
...to fetch a specific group...

2020-05-07 17:12 UTC, dusanb94 commented on docs/platform-management.md
> +You can specify `name` and/or `metadata` parameters in order to fetch specific group of things. When specifiying metadata you can specify just a part of the metadata json you want to match
specifying, JSON

2020-05-07 17:12 UTC, dusanb94 commented on docs/provision.md
> +Provision service is used to setup initial application configuration once user is created. Provision service creates  things, channels, connections, and certificates. Once user is created we can use
Provision service is used to set up...
...to create a setup...

2020-05-07 17:12 UTC, dusanb94 commented on docs/provision.md
> +Also you may use provision service to create certificates for each thing. Each service running on gateway may require more than one thing and channel for communication.
Also, you...

2020-05-07 17:12 UTC, dusanb94 commented on docs/provision.md
> +In `config.toml` we can enlist array of things and channels that we want to create and make connections between them which we call provision layout.
... enlist an array...

2020-05-07 17:12 UTC, dusanb94 commented on docs/provision.md
> +Additionally users or API token can be passed in Authorization header, this authentication takes precedence over others.
Additionally, ...

2020-05-07 17:49 UTC, manuio commented on docs/platform-management.md
> +You can specify `name` and/or `metadata` parameters in order to fetch specific group of things. When specifiying metadata you can specify just a part of the metadata json you want to match
Also, after match `.`

2020-05-07 20:51 UTC, mteodor commented on docs/platform-management.md
> +You can specify `offset` and `limit` parameters in order to fetch specific group of things. In that case, your request should look like:
i think that this is ok

2020-05-07 20:52 UTC, mteodor commented on docs/platform-management.md
> +Provisioning is a process of configuration of an IoT platform in which system operator creates and sets-up different entities used in the platform - users, channels and things.
note that this `,` is optional

2020-05-07 20:59 UTC, drasko commented on docs/platform-management.md
> +Provisioning is a process of configuration of an IoT platform in which system operator creates and sets-up different entities used in the platform - users, channels and things.
What's this comment about? Putting `,` before `and` is gramatically incorrect.

2020-05-07 21:00 UTC, mteodor commented on docs/platform-management.md
> +Provisioning is a process of configuration of an IoT platform in which system operator creates and sets-up different entities used in the platform - users, channels and things.
I think it is not

2020-05-07 21:03 UTC, manuio approved these changes
LGTM

2020-05-07 21:13 UTC, dborovcanin approved these changes

2020-05-07 21:13 UTC, merged