NOISSUE - add edge docs
absmach/supermq-docs pull request #36
Opened 2020-05-08 18:28 UTC by mteodor

2020-05-08 19:32 UTC, drasko requested changes
Regarding diagram:
- Agent comm with NATS is bidirectional
- Export has Redis Streams for local buffering
- Add some colors and write what is the Gateway (in the box)

2020-05-19 10:10 UTC, dborovcanin requested changes

2020-05-19 10:10 UTC, dusanb94 commented on docs/agent.md
> +There are two type of channels used for **Agent** `data` and `control`. Over the `control` we are sending commands and receiving response from commands.
There are two types (plural) of channels used for **Agent**: `data` and `control`.

2020-05-19 10:10 UTC, dusanb94 commented on docs/edge-deployment.md
> +Following are steps that are an example usage of Mainflux components to connect edge with cloud.
The following...

2020-05-19 10:10 UTC, dusanb94 commented on docs/edge-deployment.md
> +Using [Bootstrap](bootstrap) and [Provision](provision) we will create configuration for use in gateway deployment.
... a configuration for use...

2020-05-19 10:10 UTC, dusanb94 commented on docs/edge-deployment.md
> +These paramaters will be used by `Agent` service on the gateway to retrieve that information and establish a connection with the cloud.
...parameters... by the `Agent` service...

2020-05-19 10:10 UTC, dusanb94 commented on docs/edge.md
> +Mainflux IoT platform provides services for supporting management of devices in the edge. Typicaly, IoT solution includes devices (sensors/actuators) deployed in far edge and connected through some p
...on the edge. Tipically, ...

2020-05-19 10:10 UTC, dusanb94 commented on docs/edge.md
> +Although most devices could be connected to the Mainflux directly using gateways provides for data transmission and routing eases a process of set up. Also gateways can provide additional data proces
...a process of setting up.

2020-05-19 10:10 UTC, dusanb94 commented on docs/export.md
> +When connection is lost, messages from local bus are stored into `Redis` stream. Upon connection reestablishment `Export` service consumes messages from `Redis` stream and sends it to the Mainflux cl
... from the local bus...

2020-05-19 12:53 UTC, drasko requested changes

2020-05-19 12:53 UTC, drasko commented on docs/edge.md
> +![Edge](img/edge/edge.png)
Here you kept nice link, however up you modified to rawcontent. Why?

2020-05-19 12:53 UTC, drasko commented on docs/bootstrap.md
> +![Configure device](https://raw.githubusercontent.com/mainflux/docs/master/docs/img/bootstrap/1.png)
Do we need this? It really can not work with relative link?

2020-05-19 13:01 UTC, mteodor commented on docs/edge.md
> +![Edge](img/edge/edge.png)
you mean like this `![Edge][edge]`? it didnt work.

2020-05-19 13:05 UTC, drasko commented on docs/edge.md
> +![Edge](img/edge/edge.png)
No, this is good. But you changed the other one. Revert is good, so I resolve this one.

2020-05-19 13:06 UTC, drasko approved these changes
LGTM

2020-05-21 12:05 UTC, dborovcanin approved these changes

2020-05-21 12:05 UTC, merged