NOISSUE - Fix http request example with metadata query param
absmach/supermq-docs pull request #50
Opened 2020-09-14 10:58 UTC by mteodor

Signed-off-by: Mirko Teodorovic <mirko.teodorovic@gmail.com>

2020-09-14 11:07 UTC, manuio requested changes

2020-09-14 11:07 UTC, manuio commented on docs/platform-management.md
> +curl -s -S -i --cacert docker/ssl/certs/ca.crt -H "Authorization: <user_auth_token>" https://localhost/things?offset=0&limit=5&metadata="\{\"serial\":\"123456\"\}"
Are you sure that first `\"` is needed?

2020-09-14 11:13 UTC, mteodor commented on docs/platform-management.md
> +curl -s -S -i --cacert docker/ssl/certs/ca.crt -H "Authorization: <user_auth_token>" https://localhost/things?offset=0&limit=5&metadata="\{\"serial\":\"123456\"\}"
Yes, checked it

2020-09-14 11:14 UTC, manuio commented on docs/platform-management.md
> +curl -s -S -i --cacert docker/ssl/certs/ca.crt -H "Authorization: <user_auth_token>" https://localhost/things?offset=0&limit=5&metadata="\{\"serial\":\"123456\"\}"
Why not last one?

2020-09-14 13:41 UTC, manuio approved these changes
LGTM

2020-09-16 10:37 UTC, dusanb94 approved these changes

2020-09-16 10:37 UTC, merged