update agent doc to match the one in mainflux/agent
absmach/supermq-docs pull request #51
Opened 2020-09-24 14:38 UTC by PricelessRabbit

doc is wrong about the subject in which agent relays the service commands. 
Updated Proxying commands part to match the one in mainflux/agent repo

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2020-09-24 14:57 UTC, mteodor approved these changes, later dismissed
LGTM, thanks

2020-09-24 14:58 UTC, dusanb94 approved these changes, later dismissed

2020-09-24 14:59 UTC, manuio requested changes

2020-09-24 14:59 UTC, manuio commented on docs/agent.md
> +You can send commands to other services that are subscribed on the same edge Nats server as Agent.
Use `NATS` instead of `Nats` and try to make this sentence easier to understand, please.

2020-09-24 15:16 UTC, PricelessRabbit commented on docs/agent.md
> +You can send commands to other services that are subscribed on the same edge Nats server as Agent.
I copy / paste the text from the mainflux/agent repo. I've to update also that repo?

2020-09-24 15:21 UTC, drasko commented on docs/agent.md
> +You can send commands to other services that are subscribed on the same edge Nats server as Agent.
Yep

2020-09-24 15:49 UTC, mteodor commented on docs/agent.md
> +You can send commands to other services that are subscribed on the same edge Nats server as Agent.
Put this
You can send commands to services running on the same edge gateway as **Agent** if they are subscribed on same `NATS` server and correct subject.

2020-09-25 10:02 UTC, PricelessRabbit commented on docs/agent.md
> +You can send commands to other services that are subscribed on the same edge Nats server as Agent.
updated

2020-09-25 10:06 UTC, manuio commented on docs/agent.md
> +You can send commands to other services that are subscribed on the same edge Nats server as Agent.
Use capital letters for `Nats` -> `NATS`

2020-09-25 10:11 UTC, mteodor approved these changes

2020-09-25 10:11 UTC, manuio approved these changes
LGTM

2020-09-25 10:11 UTC, merged