MF-73 - Updated getting started doc for mainflux-cli building and docker status check
absmach/supermq-docs pull request #74
Opened 2021-03-02 06:25 UTC by dramasamy

### What does this do?

Updates the getting started document (MF-73)

### Which issue(s) does this PR fix/relate to?
Resolves #73 

### List any changes that modify/break current functionality

### Have you included tests for your changes?
Yes - `mkdocs serve`

### Did you document any new/modified functionality?

### Notes

2021-03-02 08:17 UTC, manuio requested changes

2021-03-02 08:17 UTC, manuio commented on docs/cli.md
>  ```
I'd prefer:

Get the mainflux code

```bash
go get github.com/mainflux/mainflux
```

Build the mainflux-cli

```bash
make cli
```

2021-03-02 19:21 UTC, drasko requested changes
I generally have doubts on this PR. There are some good and helpful things, but we need to find a right balance, documentation must stay extremely tight and lean, as is whole Mainflux philosophy.

2021-03-02 19:21 UTC, drasko commented on docs/getting-started.md
> +Build `mainflux-cli` if the pre-built CLI is not compatible with your OS, i.e MacOS. Please see the [CLI](cli.md) for further details.
I was not aware that CLI we build on Linux is not compatible with MacOS. Is it because of new ARM arch?

2021-03-02 19:21 UTC, drasko commented on docs/getting-started.md
> +Check the containers are up and running before proceeding.
I would remove this imperative and eventually put it under markdown quote `>` - this is nice to have, but not necessary.

2021-03-02 19:21 UTC, drasko commented on docs/getting-started.md
> +> Cleanup the container images and volumes by executing `make cleandocker` if any container is in 'Restarting' to ensure that the previous deployment doesn't affect the new one. This command removes
This is also something I do not consider necessary. Why if 'Restarting'? And I would also rather advise someone to debug the system and learn something rather than just shortcuit the problem.

Maybe it would simpler just to describe how to remove everything in the case of problems, and do not suggest exact problem.

2021-03-02 19:21 UTC, drasko commented on docs/cli.md
> +The [GOPATH](https://golang.org/doc/gopath_code) should be set and `go get` the `mainflux` code to build the cli successfully.
No need for Go basic lessons here

2021-03-02 19:21 UTC, drasko commented on docs/cli.md
> +# Get the mainflux code
No need for this. People need to figure out this.

Maybe you can tell them in your words just that CLI code is inside the mainflux repo.

2021-03-03 02:46 UTC, dramasamy commented on docs/getting-started.md
> +Build `mainflux-cli` if the pre-built CLI is not compatible with your OS, i.e MacOS. Please see the [CLI](cli.md) for further details.
`GOOS=darwin` for MacOs; that's the reason we can't use the Linux binary in MacOs.

2021-03-03 02:52 UTC, dramasamy commented on docs/getting-started.md
> +Build `mainflux-cli` if the pre-built CLI is not compatible with your OS, i.e MacOS. Please see the [CLI](cli.md) for further details.
The CLI can be used from any operating system which may be outside the Kubernetes cluster. And, it is hard to pre-build `mainflux-cli` for each operating system. Hence, it would be helpful for the user if they know how to compile CLI instead of debugging why the command doesn't work.

I agree the documentation should be slim, but the getting started info should be clean to increase the user experience.

2021-03-03 02:56 UTC, dramasamy commented on docs/getting-started.md
> +Check the containers are up and running before proceeding.
I agree, I'll remove this.

2021-03-03 02:57 UTC, dramasamy commented on docs/cli.md
> +The [GOPATH](https://golang.org/doc/gopath_code) should be set and `go get` the `mainflux` code to build the cli successfully.
I agree.

2021-03-03 02:59 UTC, dramasamy commented on docs/getting-started.md
> +> Cleanup the container images and volumes by executing `make cleandocker` if any container is in 'Restarting' to ensure that the previous deployment doesn't affect the new one. This command removes
I agree

2021-03-03 03:20 UTC, dramasamy commented on docs/cli.md
> +# Get the mainflux code
In my view, `go get` is easy and straightforward for the user instead of writing in words. If you prefer to remove it, I can. But providing `go get` helps to compile the CLI without any error on the first try which gives increases the user experience and "getting started" time is too fast.

2021-03-03 08:44 UTC, dusanb94 requested changes

2021-03-03 08:44 UTC, dusanb94 commented on docs/cli.md
> +Get the mainflux code
Get the Mainflux code:

2021-03-03 08:44 UTC, dusanb94 commented on docs/getting-started.md
> +Build `mainflux-cli` if the pre-built CLI is not compatible with your OS, i.e MacOS. Please see the [CLI](cli.md) for further details.
While I agree with this, we definitely should push at least 3 versions of CLI binary for each of the popular operating systems.

2021-03-03 18:17 UTC, nmarcetic approved these changes

2021-03-03 18:17 UTC, nmarcetic commented on docs/getting-started.md
> +Build `mainflux-cli` if the pre-built CLI is not compatible with your OS, i.e MacOS. Please see the [CLI](cli.md) for further details.
Especially now when Mac abandon Intel.

2021-03-03 23:35 UTC, drasko requested changes

2021-03-03 23:35 UTC, drasko commented on docs/cli.md
> +Get the mainflux code
I would just write here - go to the `mainflux` source dir that you fetched from the GitHub and issue `make` command:
```bash
make cli
```

But generally when you start writing this detailed documentation with instructions for developers, you are opening a can of worms. Do they use modules? Where do they fetch the code? Do you checkout stable release git tag? and so on. This is why I am against this approach.

Writing `make cli` as it is now is a good hint for anybody to put his hands in the oil. We cannot (and we should not) chew everything.

2021-03-05 02:31 UTC, dramasamy commented on docs/cli.md
> +Get the mainflux code
I agree. A Golang developer knows how to compile the code to build the binary. However, I'm worried about people who come from Python/C/Java/etc background because they might not know how to compile the binary if it is missing for their operating system.

If we have plans to pre-build the CLI for a few famous OS, this PR will become invalid and I'm completely fine with that. As of today, if someone comes from non-golang background they are stuck if the binary is not compatible.

2021-03-05 12:49 UTC, nmarcetic commented on docs/cli.md
> +Get the mainflux code
I agree with @dramasamy 
And we have a plan to pre-build multiple versions of CLI binary for release. But it's not yet set and I am totally fine with those changes. It's not like he wrote a tutorial, it's just 2-3 additional lines, which are helpful.

2021-03-22 16:33 UTC, manuio commented
@drasko What we have decided to do for this one?

2021-04-10 20:53 UTC, drasko approved these changes
LGTM

2021-04-10 20:54 UTC, drasko commented
@dramasamy please update the branch so that we can proceed with merging

2021-04-13 02:35 UTC, dramasamy commented
> @dramasamy please update the branch so that we can proceed with merging

2021-04-13 02:36 UTC, dramasamy commented
@drasko Could you let me know what you mean by 'update branch'?

2021-04-13 07:12 UTC, nmarcetic commented
> @drasko Could you let me know what you mean by 'update branch'?

@dramasamy It's our of date with a base branch (the one you started, master). You must update so we can merge. At the bottom of this page, you will see the Github message `This branch is out-of-date with the base branch` , you can try to update directly via UI. hopefully, if there are no conflicts you will be able to successfully update, otherwise, you must resolve conflicts locally and push the changes. You changed docs, I don't think you will have conflicts (just hit the Update branch button).

2021-05-20 07:42 UTC, manuio commented
@dramasamy You can update your branch from github, there is a button.

2021-05-20 18:58 UTC, drasko approved these changes
LGTM

2021-05-20 18:58 UTC, merged

2021-05-21 00:54 UTC, dramasamy commented
@drasko Sorry for delaying this much as I'm occupied with other tasks. Thanks for merging it