ISSUE-76 Add HTTP API curl request documentation
absmach/supermq-docs pull request #77
Opened 2021-03-12 14:23 UTC by fbugarski

### Which issue(s) does this PR fix/relate to?
Resolves #76

2021-03-12 14:40 UTC, blokovi commented on docs/api.md
> +curl -s -S -i -X GET -H "Authorization: token" http://localhost/users/userID
I suggest that you somehow mark the placeholders that need to be changed.
Maybe something like this:
```
curl -s -S -i -X GET -H "Authorization: {token}" http://localhost/users/{userID}
```

2021-03-12 18:32 UTC, manuio commented on docs/api.md
> +curl -s -S -i -X GET -H "Authorization: token" http://localhost/users/userID
or `$TOKEN` ?

2021-03-22 16:06 UTC, manuio requested changes

2021-03-22 16:06 UTC, manuio commented on docs/api.md
> +curl -s -S -i -X POST -H "Content-Type: application/json" -H "Authorization: <token>" http://localhost/things/bulk -d '[{"name": "thing123", "key": ""}]'
I'd remove the key or use `<key>`

2021-03-22 16:06 UTC, manuio commented on docs/api.md
> +curl -s -S -i -X POST -H "Content-Type: application/json" -H "Authorization: <token>" http://localhost/things/bulk -d '[{"name": "", "key": ""}, {"name": "", "key": ""}]'
Same here

2021-03-22 17:39 UTC, drasko requested changes

2021-03-22 17:39 UTC, drasko commented on docs/api.md
> +> Must-have: token, old_password and password(new password)
Space in front of the `(`

2021-03-22 17:39 UTC, drasko commented on docs/api.md
> +curl -s -S -i -X POST -H "Content-Type: application/json" -H "Authorization: <token>" http://localhost/things/bulk -d '[{"name": "thing123", "key": ""}]'
Yes, not empty string - someone might understand that he/she needs to put empty string here.

2021-03-22 17:39 UTC, drasko commented on docs/api.md
> +>Should-have: thing key
This is a bit confusing - is this a mandatory field, or if not why is it "should-have" then?

2021-03-22 17:45 UTC, manuio requested changes

2021-03-22 17:45 UTC, manuio commented on docs/api.md
> +{"id":"d782b42b-e317-4cd7-9dd0-4e2ea0f349c8","email":"test@email.com","groups":null}
Can we find something better than `null` here?

2021-03-22 17:45 UTC, manuio commented on docs/api.md
> +{"total":2,"offset":0,"limit":10,"Users":[{"id":"4bf4a13a-e9c3-4207-aa11-fe569986c301","email":"admin@example.com","groups":null},{"id":"d782b42b-e317-4cd7-9dd0-4e2ea0f349c8","email":"test@email.com"
same here

2021-03-22 17:45 UTC, manuio commented on docs/api.md
> +{"msg":""}
What is this?

2021-03-22 17:45 UTC, manuio commented on docs/api.md
> +curl -s -S -i -X POST -H "Content-Type: application/json" -H "Authorization: <token>" http://localhost/channels/bulk -d '[{"name": ""}, {"name": ""}]'
Maybe `myName` for the name? Otherwid remove it because is not needed

2021-03-22 17:45 UTC, manuio commented on docs/api.md
> +curl -s -S -i -X PUT -H "Content-Type: application/json" -H  "Authorization: <token>" http://localhost/channels/<channelID> -d '{"name": "channel"}'
confusing name

2021-03-22 17:45 UTC, manuio commented on docs/api.md
> +curl -s -S -i -X POST -H "Content-Type: application/json" http://localhost/identify/channels/<channelID>/access-by-id -d '{"thing_id": ""}'
Add somthing for this empty id

2021-03-22 17:52 UTC, dusanb94 commented on docs/api.md
> +curl -s -S -i -X POST -H "Content-Type: application/json" -H "Authorization: <token>" http://localhost/channels/bulk -d '[{"name": ""}, {"name": ""}]'
I would also propose using two different names ("channel1" and "channel2" according to the response) for examples. Consider adding metadata to one of them as an example, as well.

2021-03-23 14:35 UTC, manuio requested changes

2021-03-23 14:35 UTC, manuio commented on docs/api.md
> +curl -s -S -i -X POST -H "Content-Type: application/json" http://localhost/users -d '{"email":"<test@email.com>", "password":"<12345678>"}'
this should be or `"test@email.com"` or `"<user_email>"`

2021-03-23 17:00 UTC, manuio requested changes

2021-03-23 17:00 UTC, manuio commented on docs/api.md
> +curl -s -S -i -X POST -H "Content-Type: application/json" http://localhost/users -d '{"email":"<user_email.com>", "password":"<user_password>"}'
what about `.rs`?  :)

2021-03-24 08:54 UTC, manuio commented on docs/api.md
>  curl -s -S -i -X POST -H "Content-Type: application/json" -H "Authorization: <token>" http://localhost/things/bulk -d '[{"name": "<thing_name1>"}, {"name": "<thing_name2>"}]'
`<thing_name_1>` would be more readable. Same for any name with number

2021-03-24 16:14 UTC, drasko approved these changes
LGTM

2021-03-24 16:17 UTC, drasko requested changes

2021-03-24 16:17 UTC, drasko commented on docs/api.md
> +Assign user,thing or channel to a group
Space after comma

2021-03-24 16:17 UTC, drasko commented on docs/api.md
> +To create a group, you need the group name and a user_token
Maybe `user_token`, not user_token

2021-03-24 16:54 UTC, drasko approved these changes
LGTM

2021-03-24 16:54 UTC, merged