NOISSUE - Update documentation
absmach/supermq-docs pull request #81
Opened 2021-03-29 13:17 UTC by fbugarski

Merge documentation and update docs/mkdocs.yml to make it more readable in read the docs.

2021-03-29 14:42 UTC, drasko requested changes

2021-03-29 14:42 UTC, drasko commented on docs/overview.md
> +# OVERVIEW
Overview, not OVERVIEW

2021-03-29 21:20 UTC, manuio commented on mkdocs.yml
> -    - Example deployment: edge-deployment.md
Where is this now?

2021-03-29 22:03 UTC, drasko approved these changes
LGTM

2021-03-29 22:05 UTC, drasko requested changes

2021-03-29 22:05 UTC, drasko commented on mkdocs.yml
> +  - Edge: edge.md
Indeed - wait - where `agent.md` is referred? Looks like it is not at all?

2021-03-29 22:05 UTC, drasko commented on mkdocs.yml
> +  - Edge: edge.md
Looks like you just deleted it?

2021-03-29 22:26 UTC, drasko requested changes

2021-03-29 22:26 UTC, drasko commented on docs/overview.md
> +The following is a set of guidelines to contribute to Mainflux and its libraries, which are
Instead of this, just refer to the contribution guide with a link like [here](https://github.com/Mainflux/mainflux#contributing).

2021-03-29 22:26 UTC, drasko commented on docs/overview.md
> +
Just refer to the Apach-2.0 license with a link, like [here](https://github.com/Mainflux/mainflux#license). Use [this](https://www.apache.org/licenses/LICENSE-2.0) as a link reference.

2021-03-29 22:26 UTC, drasko commented on mkdocs.yml
> -    - Example deployment: edge-deployment.md
@manuio  he had to merge several files into one so that left-hand menu renders nicely in MkDocs.

2021-03-30 11:53 UTC, manuio submitted a review, later dismissed
LGTM

2021-03-30 12:08 UTC, mteodor submitted a review, later dismissed

2021-03-30 18:54 UTC, drasko approved these changes
LGTM

2021-03-30 18:54 UTC, merged