NOISSUE - Add Rules service page to documentation
absmach/supermq-docs pull request #89
Opened 2021-05-07 14:09 UTC by darkodraskovic

Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

2021-05-07 14:24 UTC, drasko requested changes

2021-05-07 14:24 UTC, drasko commented on docs/rules.md
> +
Kill those unnecessary empty lines

2021-05-20 07:32 UTC, manuio commented on docs/rules.md
> +Mainflux Rules service is build around [EMQ X Kuiper](https://github.com/emqx/kuiper), a lightweight IoT rules engine. Mainflux Rules service consists of
Maybe you can use `:` after `of`?

2021-05-20 07:32 UTC, manuio commented on docs/rules.md
> +"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjA0MjgxODAsImlhdCI6MTYyMDM5MjE4MCwiaXNzIjoibWFpbmZsdXguYXV0aCIsInN1YiI6InBlbnNpdmVfZ2FsaWxlb0BlbWFpbC5jb20iLCJpc3N1ZXJfaWQiOiI0NDlhMGE5YS04YjE5LTQwM
There is a token in the response? If yes, why it's not a JSON?

2021-06-23 18:32 UTC, drasko commented
@darkodraskovic please resolve these and let's move with this PR

2024-03-05 22:32 UTC, drasko commented
Closing, as we moved away from Kuiper RE

2024-03-05 22:32 UTC, closed without merging