NOISSUE - Improve explanation on message types for export service
absmach/supermq-docs pull request #90
Opened 2021-05-28 07:28 UTC by mteodor

### What does this do?
 improve explanation on message types for export service

2021-05-28 08:39 UTC, blokovi submitted a review, later dismissed

2021-06-11 15:44 UTC, drasko requested changes

2021-06-11 15:44 UTC, drasko commented on docs/edge.md
> +    - `mfx` is for messages that are being picked up on internal Mainflux NATS bus. When using `Export` along with Mainflux deployed on gateway ([Fig. 1](#edge)) messages coming from MQTT broker that
Probably add this link for proto to a footnote, as other are. For consistency sake.

2021-06-23 18:32 UTC, drasko commented
@mteodor please fix demanded and let's move forward with this one

2021-10-20 14:55 UTC, drasko requested changes

2021-10-20 14:55 UTC, drasko commented on docs/edge.md
> +*Fig. 1*
Center this, also write: *Figure 1* - Description of the figure

2021-10-20 14:55 UTC, drasko commented on docs/edge.md
>  Figure shows edge gateway that is running Agent, Export and minimal deployment of Mainflux services.
Re there empty spaces in the front or I am not seeing well in GitHub?

2021-10-20 14:55 UTC, drasko commented on docs/edge.md
> +
Why this 2 lines skip - would only one line skip work?

2021-11-08 10:47 UTC, drasko approved these changes
LGTM

2021-11-08 10:47 UTC, merged